# Generated by Django 5.2.17 on 2026-09-03 19:00

import django.contrib.postgres.functions
import humotech.core.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_extensions"),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('email', models.CharField(max_length=255)),
                ('password', models.TextField(db_column='password_hash')),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('LOCKED', 'LOCKED'), ('ARCHIVED', 'ARCHIVED')], max_length=30)),
                ('mfa_enabled', models.BooleanField(db_default=False)),
                ('failed_login_attempts', models.IntegerField(db_default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, db_column='last_login_at', null=True)),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserRoleScope',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('valid_from', models.DateTimeField(db_default=humotech.core.functions.TransactionNow())),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'область роли пользователя',
                'verbose_name_plural': 'области ролей пользователей',
                'db_table': 'user_role_scopes',
            },
        ),
    ]
