# Generated by Django 5.2.17 on 2026-09-03 18:44

import django.contrib.postgres.functions
import django.db.models.deletion
import django.db.models.functions.text
import humotech.core.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_extensions"),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('email', models.CharField(max_length=255)),
                ('password', models.TextField(db_column='password_hash')),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('LOCKED', 'LOCKED'), ('ARCHIVED', 'ARCHIVED')], max_length=30)),
                ('mfa_enabled', models.BooleanField(db_default=False)),
                ('failed_login_attempts', models.IntegerField(db_default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, db_column='last_login_at', null=True)),
                ('organization', models.ForeignKey(db_column='organization_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
                'db_table': 'users',
                'indexes': [models.Index(fields=['organization'], name='ix_users_organization_id')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['ACTIVE', 'INACTIVE', 'LOCKED', 'ARCHIVED'])), name='ck_users_status'), models.UniqueConstraint(models.F('organization'), django.db.models.functions.text.Lower('email'), name='uq_users_org_lower_email')],
            },
        ),
    ]
