# Generated by Django 5.2.17 on 2026-09-03 19:00

import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('employees', '0001_initial'),
        ('offices', '0001_initial'),
        ('organizations', '0001_initial'),
        ('rbac', '0001_initial'),
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee',
            field=models.ForeignKey(blank=True, db_column='employee_id', db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='userrolescope',
            name='office',
            field=models.ForeignKey(blank=True, db_column='office_id', db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='offices.office'),
        ),
        migrations.AddField(
            model_name='userrolescope',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='userrolescope',
            name='region',
            field=models.ForeignKey(blank=True, db_column='region_id', db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='regions.region'),
        ),
        migrations.AddField(
            model_name='userrolescope',
            name='role',
            field=models.ForeignKey(db_column='role_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='user_scopes', to='rbac.role'),
        ),
        migrations.AddField(
            model_name='userrolescope',
            name='user',
            field=models.ForeignKey(db_column='user_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='role_scopes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['organization'], name='ix_users_organization_id'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['ACTIVE', 'INACTIVE', 'LOCKED', 'ARCHIVED'])), name='ck_users_status'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(models.F('organization'), django.db.models.functions.text.Lower('email'), name='uq_users_org_lower_email'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('employee__isnull', False)), fields=('employee',), name='uq_users_employee_id'),
        ),
        migrations.AddIndex(
            model_name='userrolescope',
            index=models.Index(fields=['organization'], name='ix_user_role_scopes_organization_id'),
        ),
        migrations.AddIndex(
            model_name='userrolescope',
            index=models.Index(fields=['user'], name='ix_user_role_scopes_user_id'),
        ),
        migrations.AddIndex(
            model_name='userrolescope',
            index=models.Index(fields=['role'], name='ix_user_role_scopes_role_id'),
        ),
        migrations.AddConstraint(
            model_name='userrolescope',
            constraint=models.UniqueConstraint(fields=('user', 'role', 'region', 'office', 'valid_from'), name='uq_user_role_scopes_grant'),
        ),
        migrations.AddConstraint(
            model_name='userrolescope',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL('region_id IS NULL OR office_id IS NULL', [], output_field=models.BooleanField())), name='ck_user_role_scopes_scope_not_both'),
        ),
        migrations.AddConstraint(
            model_name='userrolescope',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL('valid_to IS NULL OR valid_to >= valid_from', [], output_field=models.BooleanField())), name='ck_user_role_scopes_valid_period'),
        ),
    ]
