# Generated by Django 5.2.17 on 2026-09-03 19:00

import django.contrib.postgres.functions
import django.db.models.deletion
import humotech.core.fields
import humotech.core.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_extensions"),
        ('organizations', '0001_initial'),
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('timezone', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('geofence_radius_m', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('CLOSED', 'CLOSED'), ('ARCHIVED', 'ARCHIVED')], max_length=30)),
                ('opened_at', models.DateField(blank=True, null=True)),
                ('closed_at', models.DateField(blank=True, null=True)),
                ('organization', models.ForeignKey(db_column='organization_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('region', models.ForeignKey(db_column='region_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='offices', to='regions.region')),
            ],
            options={
                'verbose_name': 'офис',
                'verbose_name_plural': 'офисы',
                'db_table': 'offices',
            },
        ),
        migrations.CreateModel(
            name='OfficeNetwork',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('name', models.CharField(max_length=100)),
                ('network_cidr', humotech.core.fields.CidrField()),
                ('is_active', models.BooleanField(db_default=True)),
                ('office', models.ForeignKey(db_column='office_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='networks', to='offices.office')),
                ('organization', models.ForeignKey(db_column='organization_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'сеть офиса',
                'verbose_name_plural': 'сети офиса',
                'db_table': 'office_networks',
            },
        ),
        migrations.AddIndex(
            model_name='office',
            index=models.Index(fields=['organization'], name='ix_offices_organization_id'),
        ),
        migrations.AddIndex(
            model_name='office',
            index=models.Index(fields=['region'], name='ix_offices_region_id'),
        ),
        migrations.AddConstraint(
            model_name='office',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uq_offices_org_code'),
        ),
        migrations.AddConstraint(
            model_name='office',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['ACTIVE', 'INACTIVE', 'CLOSED', 'ARCHIVED'])), name='ck_offices_status'),
        ),
        migrations.AddConstraint(
            model_name='office',
            constraint=models.CheckConstraint(condition=models.Q(('geofence_radius_m__isnull', True), ('geofence_radius_m__gt', 0), _connector='OR'), name='ck_offices_geofence_positive'),
        ),
        migrations.AddConstraint(
            model_name='office',
            constraint=models.CheckConstraint(condition=models.Q(('closed_at__isnull', True), ('opened_at__isnull', True), ('closed_at__gte', models.F('opened_at')), _connector='OR'), name='ck_offices_close_after_open'),
        ),
        migrations.AddIndex(
            model_name='officenetwork',
            index=models.Index(fields=['organization'], name='ix_office_networks_organization_id'),
        ),
        migrations.AddIndex(
            model_name='officenetwork',
            index=models.Index(fields=['office'], name='ix_office_networks_office_id'),
        ),
        migrations.AddConstraint(
            model_name='officenetwork',
            constraint=models.UniqueConstraint(fields=('office', 'network_cidr'), name='uq_office_networks_cidr'),
        ),
    ]
