# Generated by Django 5.2.17 on 2026-09-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
