# Generated by Django 5.2.17 on 2026-09-03 19:00

import django.contrib.postgres.functions
import django.db.models.deletion
import humotech.core.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_extensions"),
        ('employees', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('channel', models.CharField(choices=[('TELEGRAM', 'TELEGRAM'), ('EMAIL', 'EMAIL'), ('PUSH', 'PUSH'), ('IN_APP', 'IN_APP')], max_length=20)),
                ('notification_type', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SENT', 'SENT'), ('FAILED', 'FAILED'), ('CANCELLED', 'CANCELLED'), ('READ', 'READ')], max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('related_entity_type', models.CharField(blank=True, max_length=100, null=True)),
                ('related_entity_id', models.UUIDField(blank=True, null=True)),
                ('employee', models.ForeignKey(db_column='employee_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='employees.employee')),
                ('organization', models.ForeignKey(db_column='organization_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'уведомление',
                'verbose_name_plural': 'уведомления',
                'db_table': 'notifications',
                'indexes': [models.Index(fields=['organization'], name='ix_notifications_organization_id'), models.Index(fields=['employee', 'created_at'], name='ix_notifications_employee_created'), models.Index(condition=models.Q(('status', 'PENDING')), fields=['scheduled_at'], name='ix_notifications_pending')],
                'constraints': [models.CheckConstraint(condition=models.Q(('channel__in', ['TELEGRAM', 'EMAIL', 'PUSH', 'IN_APP'])), name='ck_notifications_channel'), models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'SENT', 'FAILED', 'CANCELLED', 'READ'])), name='ck_notifications_status')],
            },
        ),
    ]
