# Generated by Django 5.2.17 on 2026-09-07 12:10

import django.contrib.postgres.functions
import django.db.models.deletion
import django.db.models.expressions
import humotech.core.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_outbox_queue'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationAttempt',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('number', models.IntegerField()),
                ('attempted_at', models.DateTimeField()),
                ('outcome', models.CharField(choices=[('SENT', 'SENT'), ('FAILED', 'FAILED'), ('CANCELLED', 'CANCELLED')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('notification', models.ForeignKey(db_column='notification_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='attempt_log', to='notifications.notification')),
            ],
            options={
                'verbose_name': 'попытка отправки',
                'verbose_name_plural': 'попытки отправки',
                'db_table': 'notification_attempts',
                'indexes': [models.Index(fields=['notification', 'attempted_at'], name='ix_notification_attempts_row')],
                'constraints': [models.CheckConstraint(condition=models.Q(('outcome__in', ['SENT', 'FAILED', 'CANCELLED'])), name='ck_notification_attempts_outcome'), models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL('number >= 1', [], output_field=models.BooleanField())), name='ck_notification_attempts_number_positive'), models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL("outcome <> 'SENT' OR reason IS NULL", [], output_field=models.BooleanField())), name='ck_notification_attempts_sent_has_no_reason')],
            },
        ),
    ]
