# Generated by Django 5.2.17 on 2026-09-16 06:28

import django.contrib.postgres.functions
import django.db.models.deletion
import humotech.core.functions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_attempt_history_complete'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedRead',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('event_type', models.CharField(max_length=40)),
                ('entity_id', models.UUIDField()),
                ('read_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow())),
                ('organization', models.ForeignKey(db_column='organization_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('user', models.ForeignKey(db_column='user_id', db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'прочтение события ленты',
                'verbose_name_plural': 'прочтения событий ленты',
                'db_table': 'notification_feed_reads',
                'indexes': [models.Index(fields=['organization'], name='ix_notification_feed_reads_org'), models.Index(fields=['user', 'event_type'], name='ix_notification_feed_reads_user')],
                'constraints': [models.UniqueConstraint(fields=('user', 'event_type', 'entity_id'), name='uq_notification_feed_reads_event')],
            },
        ),
    ]
