# Generated by Django 5.2.17 on 2026-09-03 19:00

import django.contrib.postgres.functions
import django.db.models.deletion
import django.db.models.expressions
import humotech.core.functions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_extensions"),
        ('employees', '0001_initial'),
        ('knowledge', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeQuestion',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('question_text', models.TextField()),
                ('normalized_topic', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('AI_ANSWERED', 'AI_ANSWERED'), ('ESCALATED_TO_HR', 'ESCALATED_TO_HR'), ('HR_ANSWERED', 'HR_ANSWERED'), ('CLOSED', 'CLOSED')], max_length=30)),
                ('ai_answer_text', models.TextField(blank=True, null=True)),
                ('ai_confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('hr_answer_text', models.TextField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('answer_source', models.ForeignKey(blank=True, db_column='answer_source_id', db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='knowledge.knowledgesource')),
                ('assigned_to_user', models.ForeignKey(blank=True, db_column='assigned_to_user_id', db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(db_column='employee_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='employees.employee')),
                ('organization', models.ForeignKey(db_column='organization_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'вопрос сотрудника',
                'verbose_name_plural': 'вопросы сотрудников',
                'db_table': 'employee_questions',
                'indexes': [models.Index(fields=['organization'], name='ix_employee_questions_organization_id'), models.Index(fields=['employee'], name='ix_employee_questions_employee_id'), models.Index(fields=['organization', 'status'], name='ix_employee_questions_org_status')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['NEW', 'AI_ANSWERED', 'ESCALATED_TO_HR', 'HR_ANSWERED', 'CLOSED'])), name='ck_employee_questions_status'), models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL('ai_confidence IS NULL OR (ai_confidence >= 0 AND ai_confidence <= 1)', [], output_field=models.BooleanField())), name='ck_employee_questions_confidence_range')],
            },
        ),
    ]
