# Generated by Django 5.2.17 on 2026-09-03 19:00

import django.contrib.postgres.functions
import django.db.models.deletion
import django.db.models.expressions
import humotech.core.functions
import pgvector.django.indexes
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_extensions"),
        ('departments', '0001_initial'),
        ('offices', '0001_initial'),
        ('organizations', '0001_initial'),
        ('regions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeSource',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('title', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('FAQ', 'FAQ'), ('POLICY', 'POLICY'), ('INSTRUCTION', 'INSTRUCTION'), ('DOCUMENT', 'DOCUMENT')], max_length=20)),
                ('language', models.CharField(max_length=10)),
                ('content', models.TextField()),
                ('content_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('INDEXING', 'INDEXING'), ('ACTIVE', 'ACTIVE'), ('ARCHIVED', 'ARCHIVED'), ('ERROR', 'ERROR')], max_length=20)),
                ('version', models.IntegerField(db_default=1)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('priority', models.IntegerField(db_default=0)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, db_column='metadata', null=True)),
                ('approved_by_user', models.ForeignKey(blank=True, db_column='approved_by_user_id', db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by_user', models.ForeignKey(db_column='created_by_user_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, db_column='department_id', db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='departments.department')),
                ('office', models.ForeignKey(blank=True, db_column='office_id', db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='offices.office')),
                ('organization', models.ForeignKey(db_column='organization_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('parent_source', models.ForeignKey(blank=True, db_column='parent_source_id', db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='knowledge.knowledgesource')),
                ('region', models.ForeignKey(blank=True, db_column='region_id', db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='regions.region')),
            ],
            options={
                'verbose_name': 'источник знаний',
                'verbose_name_plural': 'источники знаний',
                'db_table': 'knowledge_sources',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeIndexJob',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('status', models.CharField(choices=[('QUEUED', 'QUEUED'), ('RUNNING', 'RUNNING'), ('SUCCEEDED', 'SUCCEEDED'), ('FAILED', 'FAILED')], max_length=20)),
                ('attempts', models.IntegerField(db_default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_summary', models.TextField(blank=True, null=True)),
                ('organization', models.ForeignKey(db_column='organization_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('source', models.ForeignKey(db_column='source_id', db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='index_jobs', to='knowledge.knowledgesource')),
            ],
            options={
                'verbose_name': 'задание индексации',
                'verbose_name_plural': 'задания индексации',
                'db_table': 'knowledge_index_jobs',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('chunk_index', models.IntegerField()),
                ('chunk_text', models.TextField()),
                ('token_count', models.IntegerField()),
                ('content_hash', models.CharField(max_length=64)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('meta', models.JSONField(blank=True, db_column='metadata', null=True)),
                ('organization', models.ForeignKey(db_column='organization_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('source', models.ForeignKey(db_column='source_id', db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.knowledgesource')),
            ],
            options={
                'verbose_name': 'фрагмент знаний',
                'verbose_name_plural': 'фрагменты знаний',
                'db_table': 'knowledge_chunks',
            },
        ),
        migrations.CreateModel(
            name='FaqEntry',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('canonical_question', models.TextField()),
                ('approved_answer', models.TextField()),
                ('language', models.CharField(max_length=10)),
                ('content_hash', models.CharField(max_length=64)),
                ('question_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('ACTIVE', 'ACTIVE'), ('ARCHIVED', 'ARCHIVED')], max_length=20)),
                ('priority', models.IntegerField(db_default=0)),
                ('approved_by_user', models.ForeignKey(blank=True, db_column='approved_by_user_id', db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by_user', models.ForeignKey(db_column='created_by_user_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('office', models.ForeignKey(blank=True, db_column='office_id', db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='offices.office')),
                ('organization', models.ForeignKey(db_column='organization_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('region', models.ForeignKey(blank=True, db_column='region_id', db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='regions.region')),
                ('source', models.ForeignKey(blank=True, db_column='source_id', db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faq_entries', to='knowledge.knowledgesource')),
            ],
            options={
                'verbose_name': 'запись FAQ',
                'verbose_name_plural': 'записи FAQ',
                'db_table': 'faq_entries',
            },
        ),
        migrations.AddIndex(
            model_name='knowledgesource',
            index=models.Index(fields=['organization'], name='ix_knowledge_sources_organization_id'),
        ),
        migrations.AddIndex(
            model_name='knowledgesource',
            index=models.Index(fields=['region'], name='ix_knowledge_sources_region_id'),
        ),
        migrations.AddIndex(
            model_name='knowledgesource',
            index=models.Index(fields=['office'], name='ix_knowledge_sources_office_id'),
        ),
        migrations.AddIndex(
            model_name='knowledgesource',
            index=models.Index(fields=['organization', 'status', 'language'], name='ix_knowledge_sources_lookup'),
        ),
        migrations.AddConstraint(
            model_name='knowledgesource',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'INDEXING', 'ACTIVE', 'ARCHIVED', 'ERROR'])), name='ck_knowledge_sources_status'),
        ),
        migrations.AddConstraint(
            model_name='knowledgesource',
            constraint=models.CheckConstraint(condition=models.Q(('source_type__in', ['FAQ', 'POLICY', 'INSTRUCTION', 'DOCUMENT'])), name='ck_knowledge_sources_source_type'),
        ),
        migrations.AddConstraint(
            model_name='knowledgesource',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL('version > 0', [], output_field=models.BooleanField())), name='ck_knowledge_sources_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='knowledgesource',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL('char_length(content_hash) = 64', [], output_field=models.BooleanField())), name='ck_knowledge_sources_content_hash_length'),
        ),
        migrations.AddConstraint(
            model_name='knowledgesource',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL('office_id IS NULL OR region_id IS NULL', [], output_field=models.BooleanField())), name='ck_knowledge_sources_scope_not_both'),
        ),
        migrations.AddConstraint(
            model_name='knowledgesource',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL('effective_to IS NULL OR effective_from IS NULL OR effective_to >= effective_from', [], output_field=models.BooleanField())), name='ck_knowledge_sources_effective_period'),
        ),
        migrations.AddConstraint(
            model_name='knowledgesource',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL('parent_source_id IS NULL OR parent_source_id <> id', [], output_field=models.BooleanField())), name='ck_knowledge_sources_no_self_parent'),
        ),
        migrations.AddConstraint(
            model_name='knowledgesource',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('organization', 'title', 'language'), name='uq_knowledge_sources_active_lineage'),
        ),
        migrations.AddIndex(
            model_name='knowledgeindexjob',
            index=models.Index(fields=['organization'], name='ix_knowledge_index_jobs_organization_id'),
        ),
        migrations.AddIndex(
            model_name='knowledgeindexjob',
            index=models.Index(fields=['source'], name='ix_knowledge_index_jobs_source_id'),
        ),
        migrations.AddIndex(
            model_name='knowledgeindexjob',
            index=models.Index(condition=models.Q(('status', 'QUEUED')), fields=['next_attempt_at'], name='ix_knowledge_index_jobs_queue'),
        ),
        migrations.AddConstraint(
            model_name='knowledgeindexjob',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED'])), name='ck_knowledge_index_jobs_status'),
        ),
        migrations.AddConstraint(
            model_name='knowledgeindexjob',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL('attempts >= 0', [], output_field=models.BooleanField())), name='ck_knowledge_index_jobs_attempts_non_negative'),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=models.Index(fields=['organization'], name='ix_knowledge_chunks_organization_id'),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=models.Index(fields=['source'], name='ix_knowledge_chunks_source_id'),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='ix_knowledge_chunks_embedding_cosine', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddConstraint(
            model_name='knowledgechunk',
            constraint=models.UniqueConstraint(fields=('source', 'chunk_index'), name='uq_knowledge_chunks_index'),
        ),
        migrations.AddConstraint(
            model_name='knowledgechunk',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL('chunk_index >= 0', [], output_field=models.BooleanField())), name='ck_knowledge_chunks_chunk_index_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='knowledgechunk',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL('token_count > 0', [], output_field=models.BooleanField())), name='ck_knowledge_chunks_token_count_positive'),
        ),
        migrations.AddIndex(
            model_name='faqentry',
            index=models.Index(fields=['organization'], name='ix_faq_entries_organization_id'),
        ),
        migrations.AddIndex(
            model_name='faqentry',
            index=models.Index(fields=['organization', 'status', 'language'], name='ix_faq_entries_lookup'),
        ),
        migrations.AddIndex(
            model_name='faqentry',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['question_embedding'], m=16, name='ix_faq_entries_embedding_cosine', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddConstraint(
            model_name='faqentry',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'ACTIVE', 'ARCHIVED'])), name='ck_faq_entries_status'),
        ),
        migrations.AddConstraint(
            model_name='faqentry',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL('char_length(content_hash) = 64', [], output_field=models.BooleanField())), name='ck_faq_entries_content_hash_length'),
        ),
        migrations.AddConstraint(
            model_name='faqentry',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL('office_id IS NULL OR region_id IS NULL', [], output_field=models.BooleanField())), name='ck_faq_entries_scope_not_both'),
        ),
    ]
