# Generated by Django 5.2.17 on 2026-09-03 19:00

import django.contrib.postgres.functions
import django.db.models.deletion
import django.db.models.expressions
import humotech.core.functions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_extensions"),
        ('employees', '0001_initial'),
        ('knowledge', '0001_initial'),
        ('offices', '0001_initial'),
        ('organizations', '0001_initial'),
        ('regions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LlmQueryLog',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('question_text', models.TextField(blank=True, null=True)),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('language', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('EXACT_FAQ', 'EXACT_FAQ'), ('RAG_ANSWERED', 'RAG_ANSWERED'), ('ESCALATED', 'ESCALATED'), ('PERSONAL_DATA', 'PERSONAL_DATA'), ('ERROR', 'ERROR')], max_length=20)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('prompt_version', models.CharField(blank=True, max_length=20, null=True)),
                ('retrieval_score', models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True)),
                ('retrieved_source_ids', models.JSONField(blank=True, null=True)),
                ('input_tokens', models.IntegerField(blank=True, null=True)),
                ('output_tokens', models.IntegerField(blank=True, null=True)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('cache_hit', models.BooleanField(db_default=False)),
                ('fallback_used', models.BooleanField(db_default=False)),
                ('error_code', models.CharField(blank=True, max_length=50, null=True)),
                ('anonymized_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, db_column='employee_id', db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='employees.employee')),
                ('office', models.ForeignKey(blank=True, db_column='office_id', db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='offices.office')),
                ('organization', models.ForeignKey(db_column='organization_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('region', models.ForeignKey(blank=True, db_column='region_id', db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='regions.region')),
            ],
            options={
                'verbose_name': 'обращение к ассистенту',
                'verbose_name_plural': 'обращения к ассистенту',
                'db_table': 'llm_query_logs',
            },
        ),
        migrations.CreateModel(
            name='AnswerFeedback',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('rating', models.CharField(choices=[('HELPFUL', 'HELPFUL'), ('NOT_HELPFUL', 'NOT_HELPFUL')], max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, db_column='employee_id', db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='employees.employee')),
                ('organization', models.ForeignKey(db_column='organization_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('query_log', models.ForeignKey(db_column='query_log_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='feedback', to='ai_assistant.llmquerylog')),
            ],
            options={
                'verbose_name': 'оценка ответа',
                'verbose_name_plural': 'оценки ответов',
                'db_table': 'answer_feedback',
            },
        ),
        migrations.CreateModel(
            name='UnansweredQuestion',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('normalized_hash', models.CharField(max_length=64)),
                ('question_text', models.TextField()),
                ('language', models.CharField(max_length=10)),
                ('occurrences_count', models.IntegerField(db_default=1)),
                ('first_asked_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow())),
                ('last_asked_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow())),
                ('best_retrieval_score', models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True)),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('IN_REVIEW', 'IN_REVIEW'), ('ANSWERED', 'ANSWERED'), ('IGNORED', 'IGNORED')], max_length=20)),
                ('resolution_note', models.TextField(blank=True, null=True)),
                ('assigned_to_user', models.ForeignKey(blank=True, db_column='assigned_to_user_id', db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, db_column='employee_id', db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='employees.employee')),
                ('office', models.ForeignKey(blank=True, db_column='office_id', db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='offices.office')),
                ('organization', models.ForeignKey(db_column='organization_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('region', models.ForeignKey(blank=True, db_column='region_id', db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='regions.region')),
                ('resolved_faq', models.ForeignKey(blank=True, db_column='resolved_faq_id', db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='knowledge.faqentry')),
            ],
            options={
                'verbose_name': 'неотвеченный вопрос',
                'verbose_name_plural': 'неотвеченные вопросы',
                'db_table': 'unanswered_questions',
            },
        ),
        migrations.AddIndex(
            model_name='llmquerylog',
            index=models.Index(fields=['organization'], name='ix_llm_query_logs_organization_id'),
        ),
        migrations.AddIndex(
            model_name='llmquerylog',
            index=models.Index(fields=['organization', '-created_at'], name='ix_llm_query_logs_org_time'),
        ),
        migrations.AddIndex(
            model_name='llmquerylog',
            index=models.Index(fields=['organization', 'status'], name='ix_llm_query_logs_status'),
        ),
        migrations.AddIndex(
            model_name='llmquerylog',
            index=models.Index(condition=models.Q(('anonymized_at__isnull', True)), fields=['created_at'], name='ix_llm_query_logs_retention'),
        ),
        migrations.AddConstraint(
            model_name='llmquerylog',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['EXACT_FAQ', 'RAG_ANSWERED', 'ESCALATED', 'PERSONAL_DATA', 'ERROR'])), name='ck_llm_query_logs_status'),
        ),
        migrations.AddConstraint(
            model_name='llmquerylog',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL('input_tokens IS NULL OR input_tokens >= 0', [], output_field=models.BooleanField())), name='ck_llm_query_logs_input_tokens_valid'),
        ),
        migrations.AddConstraint(
            model_name='llmquerylog',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL('output_tokens IS NULL OR output_tokens >= 0', [], output_field=models.BooleanField())), name='ck_llm_query_logs_output_tokens_valid'),
        ),
        migrations.AddConstraint(
            model_name='llmquerylog',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL('latency_ms IS NULL OR latency_ms >= 0', [], output_field=models.BooleanField())), name='ck_llm_query_logs_latency_valid'),
        ),
        migrations.AddIndex(
            model_name='answerfeedback',
            index=models.Index(fields=['organization'], name='ix_answer_feedback_organization_id'),
        ),
        migrations.AddIndex(
            model_name='answerfeedback',
            index=models.Index(fields=['query_log'], name='ix_answer_feedback_query_log_id'),
        ),
        migrations.AddConstraint(
            model_name='answerfeedback',
            constraint=models.UniqueConstraint(fields=('query_log', 'employee'), name='uq_answer_feedback_once'),
        ),
        migrations.AddConstraint(
            model_name='answerfeedback',
            constraint=models.CheckConstraint(condition=models.Q(('rating__in', ['HELPFUL', 'NOT_HELPFUL'])), name='ck_answer_feedback_rating'),
        ),
        migrations.AddIndex(
            model_name='unansweredquestion',
            index=models.Index(fields=['organization'], name='ix_unanswered_questions_organization_id'),
        ),
        migrations.AddIndex(
            model_name='unansweredquestion',
            index=models.Index(fields=['organization', 'status'], name='ix_unanswered_questions_status'),
        ),
        migrations.AddIndex(
            model_name='unansweredquestion',
            index=models.Index(fields=['organization', '-occurrences_count'], name='ix_unanswered_questions_top'),
        ),
        migrations.AddConstraint(
            model_name='unansweredquestion',
            constraint=models.UniqueConstraint(fields=('organization', 'normalized_hash', 'language', 'office', 'region'), name='uq_unanswered_questions_cluster'),
        ),
        migrations.AddConstraint(
            model_name='unansweredquestion',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['NEW', 'IN_REVIEW', 'ANSWERED', 'IGNORED'])), name='ck_unanswered_questions_status'),
        ),
        migrations.AddConstraint(
            model_name='unansweredquestion',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL('occurrences_count > 0', [], output_field=models.BooleanField())), name='ck_unanswered_questions_occurrences_positive'),
        ),
        migrations.AddConstraint(
            model_name='unansweredquestion',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL('best_retrieval_score IS NULL OR (best_retrieval_score >= 0 AND best_retrieval_score <= 1)', [], output_field=models.BooleanField())), name='ck_unanswered_questions_score_range'),
        ),
    ]
