# Generated by Django 5.2.17 on 2026-09-04 12:58

import django.contrib.postgres.functions
import django.db.models.deletion
import humotech.core.functions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('kind', models.CharField(max_length=50)),
                ('fmt', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('QUEUED', 'QUEUED'), ('RUNNING', 'RUNNING'), ('SUCCEEDED', 'SUCCEEDED'), ('FAILED', 'FAILED'), ('CANCELLED', 'CANCELLED')], db_default='QUEUED', max_length=20)),
                ('filters', models.JSONField(blank=True, null=True)),
                ('attempts', models.IntegerField(db_default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('progress_rows', models.IntegerField(db_default=0)),
                ('total_rows', models.IntegerField(blank=True, null=True)),
                ('storage_key', models.TextField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('organization', models.ForeignKey(db_column='organization_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('requested_by_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='export_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'export_jobs',
                'indexes': [models.Index(fields=['organization'], name='ix_export_jobs_organization_id'), models.Index(fields=['status', 'next_attempt_at'], name='ix_export_jobs_status_next'), models.Index(fields=['requested_by_user', '-created_at'], name='ix_export_jobs_user_time'), models.Index(fields=['expires_at'], name='ix_export_jobs_expires_at')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED'])), name='ck_export_jobs_status')],
            },
        ),
    ]
