# Generated by Django 5.2.17 on 2026-09-15 12:16

import django.contrib.postgres.functions
import django.db.models.deletion
import humotech.core.functions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('reports', '0002_export_job_foreign_keys'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('attendance', 'attendance'), ('worktime', 'worktime'), ('lateness', 'lateness'), ('absences', 'absences'), ('employees', 'employees')], max_length=30)),
                ('fmt', models.CharField(choices=[('csv', 'csv'), ('xlsx', 'xlsx')], max_length=10)),
                ('filters', models.JSONField()),
            ],
            options={
                'db_table': 'report_templates',
            },
        ),
        migrations.AddField(
            model_name='exportjob',
            name='client_request_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exportjob',
            name='hidden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exportjob',
            name='progress_done',
            field=models.IntegerField(db_default=0),
        ),
        migrations.AddField(
            model_name='exportjob',
            name='progress_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='exportjob',
            constraint=models.UniqueConstraint(condition=models.Q(('client_request_id__isnull', False)), fields=('requested_by_user', 'client_request_id'), name='uq_export_jobs_client_request'),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='owner_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['organization'], name='ix_report_templates_org_id'),
        ),
        migrations.AddConstraint(
            model_name='reporttemplate',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['attendance', 'worktime', 'lateness', 'absences', 'employees'])), name='ck_report_templates_kind'),
        ),
        migrations.AddConstraint(
            model_name='reporttemplate',
            constraint=models.CheckConstraint(condition=models.Q(('fmt__in', ['csv', 'xlsx'])), name='ck_report_templates_fmt'),
        ),
        migrations.AddConstraint(
            model_name='reporttemplate',
            constraint=models.UniqueConstraint(fields=('owner_user', 'name'), name='uq_report_templates_owner_name'),
        ),
    ]
