# Generated by Django 5.2.17 on 2026-09-03 19:00

import django.contrib.postgres.functions
import django.db.models.deletion
import django.db.models.expressions
import humotech.core.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_extensions"),
        ('offices', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('ARCHIVED', 'ARCHIVED')], max_length=30)),
                ('office', models.ForeignKey(db_column='office_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='offices.office')),
                ('organization', models.ForeignKey(db_column='organization_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('parent_department', models.ForeignKey(blank=True, db_column='parent_department_id', db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='departments.department')),
            ],
            options={
                'verbose_name': 'отдел',
                'verbose_name_plural': 'отделы',
                'db_table': 'departments',
                'indexes': [models.Index(fields=['organization'], name='ix_departments_organization_id'), models.Index(fields=['office'], name='ix_departments_office_id'), models.Index(fields=['parent_department'], name='ix_departments_parent_department_id')],
                'constraints': [models.UniqueConstraint(fields=('office', 'code'), name='uq_departments_office_code'), models.CheckConstraint(condition=models.Q(('status__in', ['ACTIVE', 'INACTIVE', 'ARCHIVED'])), name='ck_departments_status'), models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL('parent_department_id IS NULL OR parent_department_id <> id', [], output_field=models.BooleanField())), name='ck_departments_no_self_parent')],
            },
        ),
    ]
