# Generated by Django 5.2.17 on 2026-09-18 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_head_employee_foreign_key'),
        ('employees', '0005_photo_foreign_key'),
        ('offices', '0002_address_optional'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='office',
            field=models.ForeignKey(blank=True, db_column='office_id', db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='offices.office'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(condition=models.Q(('office__isnull', True)), fields=('organization', 'code'), name='uq_departments_org_code_shared'),
        ),
    ]
