# Generated by Django 5.2.17 on 2026-09-03 19:00

import django.contrib.postgres.functions
import django.db.models.deletion
import humotech.core.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_extensions"),
        ('employees', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDevice',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('device_identifier_hash', models.TextField()),
                ('device_name', models.CharField(blank=True, max_length=255, null=True)),
                ('platform', models.CharField(blank=True, max_length=30, null=True)),
                ('app_version', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('TRUSTED', 'TRUSTED'), ('REVOKED', 'REVOKED')], max_length=20)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('trusted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(db_column='employee_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='employees.employee')),
                ('organization', models.ForeignKey(db_column='organization_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'устройство сотрудника',
                'verbose_name_plural': 'устройства сотрудников',
                'db_table': 'employee_devices',
                'indexes': [models.Index(fields=['organization'], name='ix_employee_devices_organization_id'), models.Index(fields=['employee'], name='ix_employee_devices_employee_id')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'device_identifier_hash'), name='uq_employee_devices_hash'), models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'TRUSTED', 'REVOKED'])), name='ck_employee_devices_status')],
            },
        ),
    ]
