# Generated by Django 5.2.17 on 2026-09-03 19:00

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.contrib.postgres.functions
import django.db.models.deletion
import django.db.models.expressions
import humotech.core.functions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_extensions"),
        ('departments', '0001_initial'),
        ('offices', '0001_initial'),
        ('organizations', '0001_initial'),
        ('positions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('employee_number', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('corporate_email', models.CharField(blank=True, max_length=255, null=True)),
                ('personal_email', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('hire_date', models.DateField()),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('preferred_language', models.CharField(db_default='ru', max_length=10)),
                ('employment_status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('PROBATION', 'PROBATION'), ('SUSPENDED', 'SUSPENDED'), ('TERMINATED', 'TERMINATED'), ('ARCHIVED', 'ARCHIVED')], max_length=30)),
                ('telegram_connected', models.BooleanField(db_default=False)),
                ('organization', models.ForeignKey(db_column='organization_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'сотрудник',
                'verbose_name_plural': 'сотрудники',
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='EmployeeAssignment',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'FULL_TIME'), ('PART_TIME', 'PART_TIME'), ('CONTRACT', 'CONTRACT'), ('INTERN', 'INTERN')], max_length=30)),
                ('work_mode', models.CharField(choices=[('ONSITE', 'ONSITE'), ('HYBRID', 'HYBRID'), ('REMOTE', 'REMOTE')], max_length=30)),
                ('is_primary', models.BooleanField(db_default=True)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, db_column='department_id', db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='departments.department')),
                ('employee', models.ForeignKey(db_column='employee_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='employees.employee')),
                ('manager_employee', models.ForeignKey(blank=True, db_column='manager_employee_id', db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subordinate_assignments', to='employees.employee')),
                ('office', models.ForeignKey(db_column='office_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='offices.office')),
                ('organization', models.ForeignKey(db_column='organization_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('position', models.ForeignKey(blank=True, db_column='position_id', db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='positions.position')),
            ],
            options={
                'verbose_name': 'назначение сотрудника',
                'verbose_name_plural': 'назначения сотрудников',
                'db_table': 'employee_assignments',
            },
        ),
        migrations.CreateModel(
            name='EmployeeOfficeAccess',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('access_type', models.CharField(choices=[('PRIMARY', 'PRIMARY'), ('TEMPORARY', 'TEMPORARY'), ('PERMANENT', 'PERMANENT'), ('VISITOR', 'VISITOR')], max_length=30)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(db_column='employee_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='office_access', to='employees.employee')),
                ('granted_by_user', models.ForeignKey(blank=True, db_column='granted_by_user_id', db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('office', models.ForeignKey(db_column='office_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='extra_access', to='offices.office')),
                ('organization', models.ForeignKey(db_column='organization_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'доступ к офису',
                'verbose_name_plural': 'доступы к офисам',
                'db_table': 'employee_office_access',
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['organization'], name='ix_employees_organization_id'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['organization', 'employment_status'], name='ix_employees_org_status'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('organization', 'employee_number'), name='uq_employees_org_number'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(('employment_status__in', ['ACTIVE', 'PROBATION', 'SUSPENDED', 'TERMINATED', 'ARCHIVED'])), name='ck_employees_employment_status'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL('termination_date IS NULL OR termination_date >= hire_date', [], output_field=models.BooleanField())), name='ck_employees_termination_after_hire'),
        ),
        migrations.AddIndex(
            model_name='employeeassignment',
            index=models.Index(fields=['organization'], name='ix_employee_assignments_organization_id'),
        ),
        migrations.AddIndex(
            model_name='employeeassignment',
            index=models.Index(fields=['employee'], name='ix_employee_assignments_employee_id'),
        ),
        migrations.AddIndex(
            model_name='employeeassignment',
            index=models.Index(fields=['office'], name='ix_employee_assignments_office_id'),
        ),
        migrations.AddConstraint(
            model_name='employeeassignment',
            constraint=models.CheckConstraint(condition=models.Q(('employment_type__in', ['FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERN'])), name='ck_employee_assignments_employment_type'),
        ),
        migrations.AddConstraint(
            model_name='employeeassignment',
            constraint=models.CheckConstraint(condition=models.Q(('work_mode__in', ['ONSITE', 'HYBRID', 'REMOTE'])), name='ck_employee_assignments_work_mode'),
        ),
        migrations.AddConstraint(
            model_name='employeeassignment',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL('valid_to IS NULL OR valid_to >= valid_from', [], output_field=models.BooleanField())), name='ck_employee_assignments_valid_period'),
        ),
        migrations.AddConstraint(
            model_name='employeeassignment',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL('manager_employee_id IS NULL OR manager_employee_id <> employee_id', [], output_field=models.BooleanField())), name='ck_employee_assignments_no_self_manager'),
        ),
        migrations.AddConstraint(
            model_name='employeeassignment',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('is_primary', True)), expressions=[('employee_id', '='), (models.Func(models.F('valid_from'), models.F('valid_to'), models.Value('[]'), function='daterange', output_field=django.contrib.postgres.fields.ranges.DateRangeField()), '&&')], name='ex_employee_assignments_primary_overlap'),
        ),
        migrations.AddIndex(
            model_name='employeeofficeaccess',
            index=models.Index(fields=['organization'], name='ix_employee_office_access_organization_id'),
        ),
        migrations.AddIndex(
            model_name='employeeofficeaccess',
            index=models.Index(fields=['employee'], name='ix_employee_office_access_employee_id'),
        ),
        migrations.AddIndex(
            model_name='employeeofficeaccess',
            index=models.Index(fields=['office'], name='ix_employee_office_access_office_id'),
        ),
        migrations.AddConstraint(
            model_name='employeeofficeaccess',
            constraint=models.UniqueConstraint(fields=('employee', 'office', 'valid_from'), name='uq_employee_office_access_period'),
        ),
        migrations.AddConstraint(
            model_name='employeeofficeaccess',
            constraint=models.CheckConstraint(condition=models.Q(('access_type__in', ['PRIMARY', 'TEMPORARY', 'PERMANENT', 'VISITOR'])), name='ck_employee_office_access_access_type'),
        ),
        migrations.AddConstraint(
            model_name='employeeofficeaccess',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL('valid_to IS NULL OR valid_to >= valid_from', [], output_field=models.BooleanField())), name='ck_employee_office_access_valid_period'),
        ),
    ]
