# Generated by Django 5.2.17 on 2026-09-11 14:46

import django.contrib.postgres.functions
import django.db.models.deletion
import django.db.models.expressions
import humotech.core.functions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('files', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('kind', models.CharField(choices=[('IDENTITY', 'IDENTITY'), ('CONTRACT', 'CONTRACT'), ('HIRE_ORDER', 'HIRE_ORDER'), ('OTHER', 'OTHER')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('MISSING', 'MISSING'), ('UPLOADED', 'UPLOADED'), ('GENERATED_LATER', 'GENERATED_LATER'), ('REVIEW', 'REVIEW')], max_length=30)),
            ],
            options={
                'verbose_name': 'документ сотрудника',
                'verbose_name_plural': 'документы сотрудника',
                'db_table': 'employee_documents',
            },
        ),
        migrations.CreateModel(
            name='EmployeeOnboardingKey',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('key', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'ключ добавления сотрудника',
                'verbose_name_plural': 'ключи добавления сотрудников',
                'db_table': 'employee_onboarding_keys',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='pinfl',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(('pinfl__isnull', False)), fields=('organization', 'pinfl'), name='uq_employees_org_pinfl'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='employee',
            field=models.ForeignKey(db_column='employee_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='file',
            field=models.ForeignKey(blank=True, db_column='file_id', db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_documents', to='files.file'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='employeeonboardingkey',
            name='created_by_user',
            field=models.ForeignKey(db_column='created_by_user_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='employee_onboarding_keys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeonboardingkey',
            name='employee',
            field=models.ForeignKey(db_column='employee_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='onboarding_keys', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='employeeonboardingkey',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization'),
        ),
        migrations.AddIndex(
            model_name='employeedocument',
            index=models.Index(fields=['organization'], name='ix_employee_documents_org_id'),
        ),
        migrations.AddIndex(
            model_name='employeedocument',
            index=models.Index(fields=['employee'], name='ix_employee_documents_employee_id'),
        ),
        migrations.AddConstraint(
            model_name='employeedocument',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['IDENTITY', 'CONTRACT', 'HIRE_ORDER', 'OTHER'])), name='ck_employee_documents_kind'),
        ),
        migrations.AddConstraint(
            model_name='employeedocument',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['MISSING', 'UPLOADED', 'GENERATED_LATER', 'REVIEW'])), name='ck_employee_documents_status'),
        ),
        migrations.AddConstraint(
            model_name='employeedocument',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'OTHER'), _negated=True), fields=('employee', 'kind'), name='uq_employee_documents_kind'),
        ),
        migrations.AddConstraint(
            model_name='employeedocument',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL("status <> 'UPLOADED' OR file_id IS NOT NULL", [], output_field=models.BooleanField())), name='ck_employee_documents_uploaded_has_file'),
        ),
        migrations.AddIndex(
            model_name='employeeonboardingkey',
            index=models.Index(fields=['organization'], name='ix_employee_onboarding_org_id'),
        ),
        migrations.AddConstraint(
            model_name='employeeonboardingkey',
            constraint=models.UniqueConstraint(fields=('organization', 'key'), name='uq_employee_onboarding_keys'),
        ),
    ]
