# Generated by Django 5.2.17 on 2026-09-13 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_onboarding_foreign_keys'),
        ('files', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('SINGLE', 'SINGLE'), ('MARRIED', 'MARRIED'), ('DIVORCED', 'DIVORCED'), ('WIDOWED', 'WIDOWED')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ForeignKey(blank=True, db_column='photo_file_id', db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='files.file'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(('gender__isnull', True), ('gender__in', ['MALE', 'FEMALE']), _connector='OR'), name='ck_employees_gender'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(('marital_status__isnull', True), ('marital_status__in', ['SINGLE', 'MARRIED', 'DIVORCED', 'WIDOWED']), _connector='OR'), name='ck_employees_marital_status'),
        ),
    ]
