# Generated by Django 5.2.17 on 2026-09-25 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_probation_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='mentor_employee',
            field=models.ForeignKey(blank=True, db_column='mentor_employee_id', db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='employees.employee'),
        ),
    ]
