# Generated by Django 5.2.17 on 2026-09-03 19:00

import django.contrib.postgres.functions
import django.db.models.deletion
import django.db.models.expressions
import humotech.core.functions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_extensions"),
        ('employees', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('storage_provider', models.CharField(max_length=50)),
                ('storage_key', models.TextField()),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('size_bytes', models.BigIntegerField()),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('scan_status', models.CharField(choices=[('PENDING', 'PENDING'), ('CLEAN', 'CLEAN'), ('INFECTED', 'INFECTED'), ('FAILED', 'FAILED')], max_length=20)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(db_column='organization_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('uploaded_by_employee', models.ForeignKey(blank=True, db_column='uploaded_by_employee_id', db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='employees.employee')),
                ('uploaded_by_user', models.ForeignKey(blank=True, db_column='uploaded_by_user_id', db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'файл',
                'verbose_name_plural': 'файлы',
                'db_table': 'files',
                'indexes': [models.Index(fields=['organization'], name='ix_files_organization_id')],
                'constraints': [models.UniqueConstraint(models.F('storage_provider'), models.F('storage_key'), name='uq_files_storage_key'), models.CheckConstraint(condition=models.Q(('scan_status__in', ['PENDING', 'CLEAN', 'INFECTED', 'FAILED'])), name='ck_files_scan_status'), models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL('size_bytes >= 0', [], output_field=models.BooleanField())), name='ck_files_size_non_negative'), models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL('char_length(checksum_sha256) = 64', [], output_field=models.BooleanField())), name='ck_files_checksum_length')],
            },
        ),
    ]
