# Generated by Django 5.2.17 on 2026-09-03 19:00

import django.contrib.postgres.functions
import django.db.models.deletion
import humotech.core.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_extensions"),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'разрешение',
                'verbose_name_plural': 'разрешения',
                'db_table': 'permissions',
                'constraints': [models.UniqueConstraint(fields=('code',), name='uq_permissions_code')],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_system', models.BooleanField(db_default=False)),
                ('organization', models.ForeignKey(blank=True, db_column='organization_id', db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roles', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'роль',
                'verbose_name_plural': 'роли',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('pk', models.CompositePrimaryKey('role', 'permission', blank=True, editable=False, primary_key=True, serialize=False)),
                ('permission', models.ForeignKey(db_column='permission_id', db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='role_links', to='rbac.permission')),
                ('role', models.ForeignKey(db_column='role_id', db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='permission_links', to='rbac.role')),
            ],
            options={
                'verbose_name': 'разрешение роли',
                'verbose_name_plural': 'разрешения ролей',
                'db_table': 'role_permissions',
            },
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['organization'], name='ix_roles_organization_id'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', True)), fields=('code',), name='uq_roles_system_code'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', False)), fields=('organization', 'code'), name='uq_roles_org_code'),
        ),
    ]
