# Generated by Django 5.2.17 on 2026-09-03 19:00

import django.contrib.postgres.functions
import django.db.models.deletion
import humotech.core.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_extensions"),
        ('employees', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramAccount',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('telegram_user_id', models.BigIntegerField()),
                ('telegram_chat_id', models.BigIntegerField()),
                ('telegram_username', models.CharField(blank=True, max_length=255, null=True)),
                ('language_code', models.CharField(db_default='ru', max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('REVOKED', 'REVOKED'), ('BLOCKED', 'BLOCKED')], max_length=20)),
                ('connected_at', models.DateTimeField()),
                ('last_interaction_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(db_column='employee_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='telegram_account', to='employees.employee')),
                ('organization', models.ForeignKey(db_column='organization_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'привязка Telegram',
                'verbose_name_plural': 'привязки Telegram',
                'db_table': 'telegram_accounts',
                'indexes': [models.Index(fields=['organization'], name='ix_telegram_accounts_organization_id')],
                'constraints': [models.UniqueConstraint(fields=('employee',), name='uq_telegram_accounts_employee'), models.UniqueConstraint(fields=('telegram_user_id',), name='uq_telegram_accounts_tg_user'), models.CheckConstraint(condition=models.Q(('status__in', ['ACTIVE', 'REVOKED', 'BLOCKED'])), name='ck_telegram_accounts_status')],
            },
        ),
    ]
