# Generated by Django 5.2.17 on 2026-09-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0003_link_invitation_foreign_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramlinkinvitation',
            name='expected_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
