# Generated by Django 5.2.17 on 2026-09-03 19:00

import django.contrib.postgres.functions
import humotech.core.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_extensions"),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceAction',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('action', models.CharField(choices=[('CREATED', 'CREATED'), ('SUBMITTED', 'SUBMITTED'), ('TAKEN_IN_REVIEW', 'TAKEN_IN_REVIEW'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('CANCELLED', 'CANCELLED'), ('DOCUMENT_ATTACHED', 'DOCUMENT_ATTACHED'), ('DOCUMENT_VERIFIED', 'DOCUMENT_VERIFIED'), ('COMMENTED', 'COMMENTED')], max_length=30)),
                ('previous_status', models.CharField(blank=True, max_length=20, null=True)),
                ('new_status', models.CharField(blank=True, max_length=20, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'действие по заявке',
                'verbose_name_plural': 'действия по заявкам',
                'db_table': 'absence_actions',
            },
        ),
        migrations.CreateModel(
            name='AbsenceDocument',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('document_type', models.CharField(max_length=50)),
                ('verification_status', models.CharField(choices=[('PENDING', 'PENDING'), ('VERIFIED', 'VERIFIED'), ('REJECTED', 'REJECTED')], max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'документ отсутствия',
                'verbose_name_plural': 'документы отсутствия',
                'db_table': 'absence_documents',
            },
        ),
        migrations.CreateModel(
            name='AbsenceRequest',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('request_kind', models.CharField(choices=[('CREATE', 'CREATE'), ('EXTEND', 'EXTEND'), ('CANCEL', 'CANCEL')], max_length=20)),
                ('requested_start_at', models.DateTimeField(blank=True, null=True)),
                ('requested_end_at', models.DateTimeField(blank=True, null=True)),
                ('employee_comment', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('SUBMITTED', 'SUBMITTED'), ('IN_REVIEW', 'IN_REVIEW'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('CANCELLED', 'CANCELLED')], max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'заявка на отсутствие',
                'verbose_name_plural': 'заявки на отсутствие',
                'db_table': 'absence_requests',
            },
        ),
        migrations.CreateModel(
            name='AbsenceType',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('is_paid', models.BooleanField(db_default=False)),
                ('requires_approval', models.BooleanField(db_default=True)),
                ('requires_document', models.BooleanField(db_default=False)),
                ('document_required_after_days', models.IntegerField(blank=True, null=True)),
                ('deducts_leave_balance', models.BooleanField(db_default=False)),
                ('is_active', models.BooleanField(db_default=True)),
            ],
            options={
                'verbose_name': 'вид отсутствия',
                'verbose_name_plural': 'виды отсутствия',
                'db_table': 'absence_types',
            },
        ),
        migrations.CreateModel(
            name='EmployeeAbsence',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('PLANNED', 'PLANNED'), ('ACTIVE', 'ACTIVE'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED')], max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'отсутствие сотрудника',
                'verbose_name_plural': 'отсутствия сотрудников',
                'db_table': 'employee_absences',
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('year', models.SmallIntegerField()),
                ('allocated_minutes', models.IntegerField(db_default=0)),
                ('used_minutes', models.IntegerField(db_default=0)),
                ('reserved_minutes', models.IntegerField(db_default=0)),
                ('adjustment_minutes', models.IntegerField(db_default=0)),
            ],
            options={
                'verbose_name': 'баланс отпуска',
                'verbose_name_plural': 'балансы отпусков',
                'db_table': 'leave_balances',
            },
        ),
    ]
