# Generated by Django 5.2.17 on 2026-09-03 19:00

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('absences', '0001_initial'),
        ('employees', '0001_initial'),
        ('files', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='absenceaction',
            name='actor_employee',
            field=models.ForeignKey(blank=True, db_column='actor_employee_id', db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='absenceaction',
            name='actor_user',
            field=models.ForeignKey(blank=True, db_column='actor_user_id', db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='absenceaction',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='absencedocument',
            name='file',
            field=models.ForeignKey(db_column='file_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='absence_documents', to='files.file'),
        ),
        migrations.AddField(
            model_name='absencedocument',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='absencedocument',
            name='verified_by_user',
            field=models.ForeignKey(blank=True, db_column='verified_by_user_id', db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='absencerequest',
            name='employee',
            field=models.ForeignKey(db_column='employee_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='absence_requests', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='absencerequest',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='absencerequest',
            name='parent_request',
            field=models.ForeignKey(blank=True, db_column='parent_request_id', db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derived_requests', to='absences.absencerequest'),
        ),
        migrations.AddField(
            model_name='absencerequest',
            name='reviewed_by_user',
            field=models.ForeignKey(blank=True, db_column='reviewed_by_user_id', db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='absencedocument',
            name='absence_request',
            field=models.ForeignKey(db_column='absence_request_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='absences.absencerequest'),
        ),
        migrations.AddField(
            model_name='absenceaction',
            name='absence_request',
            field=models.ForeignKey(db_column='absence_request_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='absences.absencerequest'),
        ),
        migrations.AddField(
            model_name='absencetype',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='absencerequest',
            name='absence_type',
            field=models.ForeignKey(db_column='absence_type_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='absences.absencetype'),
        ),
        migrations.AddField(
            model_name='employeeabsence',
            name='absence_type',
            field=models.ForeignKey(db_column='absence_type_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='absences', to='absences.absencetype'),
        ),
        migrations.AddField(
            model_name='employeeabsence',
            name='employee',
            field=models.ForeignKey(db_column='employee_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='absences', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='employeeabsence',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='employeeabsence',
            name='origin_request',
            field=models.ForeignKey(db_column='origin_request_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='absences', to='absences.absencerequest'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='absence_type',
            field=models.ForeignKey(db_column='absence_type_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='absences.absencetype'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='employee',
            field=models.ForeignKey(db_column='employee_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='leave_balances', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization'),
        ),
        migrations.AddIndex(
            model_name='absencedocument',
            index=models.Index(fields=['organization'], name='ix_absence_documents_organization_id'),
        ),
        migrations.AddIndex(
            model_name='absencedocument',
            index=models.Index(fields=['absence_request'], name='ix_absence_documents_absence_request_id'),
        ),
        migrations.AddConstraint(
            model_name='absencedocument',
            constraint=models.UniqueConstraint(fields=('absence_request', 'file'), name='uq_absence_documents_file'),
        ),
        migrations.AddConstraint(
            model_name='absencedocument',
            constraint=models.CheckConstraint(condition=models.Q(('verification_status__in', ['PENDING', 'VERIFIED', 'REJECTED'])), name='ck_absence_documents_verification_status'),
        ),
        migrations.AddIndex(
            model_name='absenceaction',
            index=models.Index(fields=['organization'], name='ix_absence_actions_organization_id'),
        ),
        migrations.AddIndex(
            model_name='absenceaction',
            index=models.Index(fields=['absence_request'], name='ix_absence_actions_absence_request_id'),
        ),
        migrations.AddConstraint(
            model_name='absenceaction',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ['CREATED', 'SUBMITTED', 'TAKEN_IN_REVIEW', 'APPROVED', 'REJECTED', 'CANCELLED', 'DOCUMENT_ATTACHED', 'DOCUMENT_VERIFIED', 'COMMENTED'])), name='ck_absence_actions_action'),
        ),
        migrations.AddIndex(
            model_name='absencetype',
            index=models.Index(fields=['organization'], name='ix_absence_types_organization_id'),
        ),
        migrations.AddConstraint(
            model_name='absencetype',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uq_absence_types_org_code'),
        ),
        migrations.AddConstraint(
            model_name='absencetype',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL('document_required_after_days IS NULL OR document_required_after_days >= 0', [], output_field=models.BooleanField())), name='ck_absence_types_document_days_non_negative'),
        ),
        migrations.AddIndex(
            model_name='absencerequest',
            index=models.Index(fields=['organization'], name='ix_absence_requests_organization_id'),
        ),
        migrations.AddIndex(
            model_name='absencerequest',
            index=models.Index(fields=['employee'], name='ix_absence_requests_employee_id'),
        ),
        migrations.AddIndex(
            model_name='absencerequest',
            index=models.Index(fields=['organization', 'status'], name='ix_absence_requests_status'),
        ),
        migrations.AddConstraint(
            model_name='absencerequest',
            constraint=models.CheckConstraint(condition=models.Q(('request_kind__in', ['CREATE', 'EXTEND', 'CANCEL'])), name='ck_absence_requests_request_kind'),
        ),
        migrations.AddConstraint(
            model_name='absencerequest',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'SUBMITTED', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'CANCELLED'])), name='ck_absence_requests_status'),
        ),
        migrations.AddConstraint(
            model_name='absencerequest',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL('requested_end_at IS NULL OR requested_start_at IS NULL OR requested_end_at >= requested_start_at', [], output_field=models.BooleanField())), name='ck_absence_requests_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='absencerequest',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL("request_kind = 'CREATE' OR parent_request_id IS NOT NULL", [], output_field=models.BooleanField())), name='ck_absence_requests_derived_needs_parent'),
        ),
        migrations.AddConstraint(
            model_name='absencerequest',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL('parent_request_id IS NULL OR parent_request_id <> id', [], output_field=models.BooleanField())), name='ck_absence_requests_no_self_parent'),
        ),
        migrations.AddIndex(
            model_name='employeeabsence',
            index=models.Index(fields=['organization'], name='ix_employee_absences_organization_id'),
        ),
        migrations.AddIndex(
            model_name='employeeabsence',
            index=models.Index(fields=['employee'], name='ix_employee_absences_employee_id'),
        ),
        migrations.AddIndex(
            model_name='employeeabsence',
            index=models.Index(fields=['employee', 'start_at', 'end_at'], name='ix_employee_absences_period'),
        ),
        migrations.AddConstraint(
            model_name='employeeabsence',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PLANNED', 'ACTIVE', 'COMPLETED', 'CANCELLED'])), name='ck_employee_absences_status'),
        ),
        migrations.AddConstraint(
            model_name='employeeabsence',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL('end_at >= start_at', [], output_field=models.BooleanField())), name='ck_employee_absences_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='leavebalance',
            index=models.Index(fields=['organization'], name='ix_leave_balances_organization_id'),
        ),
        migrations.AddIndex(
            model_name='leavebalance',
            index=models.Index(fields=['employee'], name='ix_leave_balances_employee_id'),
        ),
        migrations.AddConstraint(
            model_name='leavebalance',
            constraint=models.UniqueConstraint(fields=('employee', 'absence_type', 'year'), name='uq_leave_balances_year'),
        ),
        migrations.AddConstraint(
            model_name='leavebalance',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL('year >= 2000 AND year <= 2200', [], output_field=models.BooleanField())), name='ck_leave_balances_year_range'),
        ),
        migrations.AddConstraint(
            model_name='leavebalance',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL('allocated_minutes >= 0', [], output_field=models.BooleanField())), name='ck_leave_balances_allocated_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='leavebalance',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL('used_minutes >= 0', [], output_field=models.BooleanField())), name='ck_leave_balances_used_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='leavebalance',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL('reserved_minutes >= 0', [], output_field=models.BooleanField())), name='ck_leave_balances_reserved_non_negative'),
        ),
    ]
