# Generated by Django 5.2.17 on 2026-09-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='absenceaction',
            name='ck_absence_actions_action',
        ),
        migrations.AlterField(
            model_name='absenceaction',
            name='action',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('SUBMITTED', 'SUBMITTED'), ('TAKEN_IN_REVIEW', 'TAKEN_IN_REVIEW'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('CANCELLED', 'CANCELLED'), ('DOCUMENT_ATTACHED', 'DOCUMENT_ATTACHED'), ('DOCUMENT_VERIFIED', 'DOCUMENT_VERIFIED'), ('DOCUMENT_REJECTED', 'DOCUMENT_REJECTED'), ('COMMENTED', 'COMMENTED')], max_length=30),
        ),
        migrations.AddConstraint(
            model_name='absenceaction',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ['CREATED', 'SUBMITTED', 'TAKEN_IN_REVIEW', 'APPROVED', 'REJECTED', 'CANCELLED', 'DOCUMENT_ATTACHED', 'DOCUMENT_VERIFIED', 'DOCUMENT_REJECTED', 'COMMENTED'])), name='ck_absence_actions_action'),
        ),
    ]
