# Generated by Django 5.2.17 on 2026-09-18 07:22

import django.contrib.postgres.functions
import django.db.models.deletion
import django.db.models.expressions
import humotech.core.functions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0005_photo_foreign_key'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyCampaign',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('SCHEDULED', 'SCHEDULED'), ('ACTIVE', 'ACTIVE'), ('FINISHED', 'FINISHED'), ('CANCELLED', 'CANCELLED')], max_length=20)),
                ('audience_kind', models.CharField(choices=[('EMPLOYEES', 'EMPLOYEES'), ('DEPARTMENT', 'DEPARTMENT'), ('OFFICE', 'OFFICE'), ('ALL', 'ALL')], max_length=20)),
                ('audience_ids', models.JSONField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('repeat_months', models.IntegerField(blank=True, null=True)),
                ('next_send_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_user', models.ForeignKey(blank=True, db_column='created_by_user_id', db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(db_column='organization_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'рассылка опроса',
                'verbose_name_plural': 'рассылки опросов',
                'db_table': 'survey_campaigns',
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('position', models.IntegerField()),
                ('text', models.TextField()),
                ('kind', models.CharField(choices=[('SINGLE', 'SINGLE'), ('MULTI', 'MULTI'), ('SCALE', 'SCALE'), ('TEXT', 'TEXT')], max_length=20)),
                ('is_required', models.BooleanField(db_default=True)),
                ('options', models.JSONField(blank=True, null=True)),
                ('organization', models.ForeignKey(db_column='organization_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'вопрос опроса',
                'verbose_name_plural': 'вопросы опроса',
                'db_table': 'survey_questions',
            },
        ),
        migrations.CreateModel(
            name='SurveyRecipient',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SENT', 'SENT'), ('STARTED', 'STARTED'), ('COMPLETED', 'COMPLETED')], max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(db_column='campaign_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='recipients', to='surveys.surveycampaign')),
                ('employee', models.ForeignKey(db_column='employee_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='survey_recipients', to='employees.employee')),
                ('organization', models.ForeignKey(db_column='organization_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'получатель опроса',
                'verbose_name_plural': 'получатели опроса',
                'db_table': 'survey_recipients',
            },
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('text', models.TextField(blank=True, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('options', models.JSONField(blank=True, null=True)),
                ('answered_at', models.DateTimeField()),
                ('organization', models.ForeignKey(db_column='organization_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('question', models.ForeignKey(db_column='question_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='surveys.surveyquestion')),
                ('recipient', models.ForeignKey(db_column='recipient_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='surveys.surveyrecipient')),
            ],
            options={
                'verbose_name': 'ответ на вопрос',
                'verbose_name_plural': 'ответы на вопросы',
                'db_table': 'survey_answers',
            },
        ),
        migrations.CreateModel(
            name='SurveyTemplate',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by_user', models.ForeignKey(blank=True, db_column='created_by_user_id', db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(db_column='organization_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'шаблон опроса',
                'verbose_name_plural': 'шаблоны опросов',
                'db_table': 'survey_templates',
            },
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='template',
            field=models.ForeignKey(db_column='template_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='surveys.surveytemplate'),
        ),
        migrations.AddField(
            model_name='surveycampaign',
            name='template',
            field=models.ForeignKey(db_column='template_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='surveys.surveytemplate'),
        ),
        migrations.AddIndex(
            model_name='surveyrecipient',
            index=models.Index(fields=['organization'], name='ix_survey_recipients_organization_id'),
        ),
        migrations.AddIndex(
            model_name='surveyrecipient',
            index=models.Index(fields=['campaign'], name='ix_survey_recipients_campaign_id'),
        ),
        migrations.AddIndex(
            model_name='surveyrecipient',
            index=models.Index(fields=['employee'], name='ix_survey_recipients_employee_id'),
        ),
        migrations.AddConstraint(
            model_name='surveyrecipient',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'SENT', 'STARTED', 'COMPLETED'])), name='ck_survey_recipients_status'),
        ),
        migrations.AddConstraint(
            model_name='surveyrecipient',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL("status <> 'COMPLETED' OR completed_at IS NOT NULL", [], output_field=models.BooleanField())), name='ck_survey_recipients_completed_has_time'),
        ),
        migrations.AddConstraint(
            model_name='surveyrecipient',
            constraint=models.UniqueConstraint(fields=('campaign', 'employee'), name='uq_survey_recipients_campaign_employee'),
        ),
        migrations.AddIndex(
            model_name='surveyanswer',
            index=models.Index(fields=['organization'], name='ix_survey_answers_organization_id'),
        ),
        migrations.AddIndex(
            model_name='surveyanswer',
            index=models.Index(fields=['recipient'], name='ix_survey_answers_recipient_id'),
        ),
        migrations.AddIndex(
            model_name='surveyanswer',
            index=models.Index(fields=['question'], name='ix_survey_answers_question_id'),
        ),
        migrations.AddConstraint(
            model_name='surveyanswer',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL('text IS NOT NULL OR number IS NOT NULL OR options IS NOT NULL', [], output_field=models.BooleanField())), name='ck_survey_answers_has_value'),
        ),
        migrations.AddConstraint(
            model_name='surveyanswer',
            constraint=models.UniqueConstraint(fields=('recipient', 'question'), name='uq_survey_answers_recipient_question'),
        ),
        migrations.AddIndex(
            model_name='surveytemplate',
            index=models.Index(fields=['organization'], name='ix_survey_templates_organization_id'),
        ),
        migrations.AddIndex(
            model_name='surveyquestion',
            index=models.Index(fields=['organization'], name='ix_survey_questions_organization_id'),
        ),
        migrations.AddIndex(
            model_name='surveyquestion',
            index=models.Index(fields=['template'], name='ix_survey_questions_template_id'),
        ),
        migrations.AddConstraint(
            model_name='surveyquestion',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['SINGLE', 'MULTI', 'SCALE', 'TEXT'])), name='ck_survey_questions_kind'),
        ),
        migrations.AddConstraint(
            model_name='surveyquestion',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL('position > 0', [], output_field=models.BooleanField())), name='ck_survey_questions_position_positive'),
        ),
        migrations.AddConstraint(
            model_name='surveyquestion',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL("(kind IN ('SINGLE', 'MULTI') AND options IS NOT NULL) OR (kind IN ('SCALE', 'TEXT') AND options IS NULL)", [], output_field=models.BooleanField())), name='ck_survey_questions_options_match_kind'),
        ),
        migrations.AddConstraint(
            model_name='surveyquestion',
            constraint=models.UniqueConstraint(fields=('template', 'position'), name='uq_survey_questions_template_position'),
        ),
        migrations.AddIndex(
            model_name='surveycampaign',
            index=models.Index(fields=['organization'], name='ix_survey_campaigns_organization_id'),
        ),
        migrations.AddIndex(
            model_name='surveycampaign',
            index=models.Index(fields=['template'], name='ix_survey_campaigns_template_id'),
        ),
        migrations.AddIndex(
            model_name='surveycampaign',
            index=models.Index(condition=models.Q(('next_send_at__isnull', False)), fields=['next_send_at'], name='ix_survey_campaigns_next_send_at'),
        ),
        migrations.AddConstraint(
            model_name='surveycampaign',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'SCHEDULED', 'ACTIVE', 'FINISHED', 'CANCELLED'])), name='ck_survey_campaigns_status'),
        ),
        migrations.AddConstraint(
            model_name='surveycampaign',
            constraint=models.CheckConstraint(condition=models.Q(('audience_kind__in', ['EMPLOYEES', 'DEPARTMENT', 'OFFICE', 'ALL'])), name='ck_survey_campaigns_audience_kind'),
        ),
        migrations.AddConstraint(
            model_name='surveycampaign',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL('repeat_months IS NULL OR repeat_months IN (2, 3)', [], output_field=models.BooleanField())), name='ck_survey_campaigns_repeat_months'),
        ),
    ]
