# Generated by Django 5.2.17 on 2026-09-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_audience_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveycampaign',
            name='is_anonymous',
            field=models.BooleanField(db_default=False),
        ),
    ]
