# Generated by Django 5.2.17 on 2026-09-03 19:00

import django.contrib.postgres.functions
import django.db.models.deletion
import humotech.core.functions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_extensions"),
        ('employees', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.UUIDField()),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow())),
                ('actor_employee', models.ForeignKey(blank=True, db_column='actor_employee_id', db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='employees.employee')),
                ('actor_user', models.ForeignKey(blank=True, db_column='actor_user_id', db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(db_column='organization_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'запись аудита',
                'verbose_name_plural': 'журнал аудита',
                'db_table': 'audit_logs',
                'indexes': [models.Index(fields=['organization'], name='ix_audit_logs_organization_id'), models.Index(fields=['entity_type', 'entity_id', '-occurred_at'], name='ix_audit_logs_entity'), models.Index(fields=['actor_user', '-occurred_at'], name='ix_audit_logs_actor_user'), models.Index(fields=['organization', '-occurred_at'], name='ix_audit_logs_org_time')],
            },
        ),
    ]
