# Generated by Django 5.2.17 on 2026-09-03 19:00

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.contrib.postgres.functions
import django.db.models.deletion
import django.db.models.expressions
import humotech.core.functions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_extensions"),
        ('employees', '0001_initial'),
        ('offices', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('timezone', models.CharField(max_length=100)),
                ('weekly_minutes', models.IntegerField()),
                ('late_grace_minutes', models.IntegerField(db_default=0)),
                ('early_leave_grace_minutes', models.IntegerField(db_default=0)),
                ('is_flexible', models.BooleanField(db_default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('ARCHIVED', 'ARCHIVED')], max_length=30)),
                ('organization', models.ForeignKey(db_column='organization_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'рабочий график',
                'verbose_name_plural': 'рабочие графики',
                'db_table': 'work_schedules',
            },
        ),
        migrations.CreateModel(
            name='ScheduleDay',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('weekday', models.SmallIntegerField()),
                ('is_working_day', models.BooleanField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('crosses_midnight', models.BooleanField(db_default=False)),
                ('schedule', models.ForeignKey(db_column='schedule_id', db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='days', to='schedules.workschedule')),
            ],
            options={
                'verbose_name': 'день графика',
                'verbose_name_plural': 'дни графика',
                'db_table': 'schedule_days',
            },
        ),
        migrations.CreateModel(
            name='EmployeeScheduleAssignment',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('assigned_by_user', models.ForeignKey(blank=True, db_column='assigned_by_user_id', db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(db_column='employee_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_assignments', to='employees.employee')),
                ('organization', models.ForeignKey(db_column='organization_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('schedule', models.ForeignKey(db_column='schedule_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='employee_assignments', to='schedules.workschedule')),
            ],
            options={
                'verbose_name': 'назначение графика',
                'verbose_name_plural': 'назначения графиков',
                'db_table': 'employee_schedule_assignments',
            },
        ),
        migrations.CreateModel(
            name='CalendarException',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('exception_type', models.CharField(choices=[('HOLIDAY', 'HOLIDAY'), ('SHORT_DAY', 'SHORT_DAY'), ('WORKING_WEEKEND', 'WORKING_WEEKEND'), ('CLOSURE', 'CLOSURE')], max_length=30)),
                ('is_working_day', models.BooleanField()),
                ('office', models.ForeignKey(blank=True, db_column='office_id', db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calendar_exceptions', to='offices.office')),
                ('organization', models.ForeignKey(db_column='organization_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'исключение календаря',
                'verbose_name_plural': 'исключения календаря',
                'db_table': 'calendar_exceptions',
                'indexes': [models.Index(fields=['organization'], name='ix_calendar_exceptions_organization_id'), models.Index(fields=['office'], name='ix_calendar_exceptions_office_id')],
                'constraints': [models.CheckConstraint(condition=models.Q(('exception_type__in', ['HOLIDAY', 'SHORT_DAY', 'WORKING_WEEKEND', 'CLOSURE'])), name='ck_calendar_exceptions_exception_type'), models.UniqueConstraint(condition=models.Q(('office__isnull', False)), fields=('office', 'date'), name='uq_calendar_exceptions_office_date'), models.UniqueConstraint(condition=models.Q(('office__isnull', True)), fields=('organization', 'date'), name='uq_calendar_exceptions_org_date')],
            },
        ),
        migrations.CreateModel(
            name='ScheduleBreak',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_paid', models.BooleanField(db_default=False)),
                ('schedule_day', models.ForeignKey(db_column='schedule_day_id', db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='schedules.scheduleday')),
            ],
            options={
                'verbose_name': 'перерыв',
                'verbose_name_plural': 'перерывы',
                'db_table': 'schedule_breaks',
                'indexes': [models.Index(fields=['schedule_day'], name='ix_schedule_breaks_schedule_day_id')],
            },
        ),
        migrations.AddIndex(
            model_name='workschedule',
            index=models.Index(fields=['organization'], name='ix_work_schedules_organization_id'),
        ),
        migrations.AddConstraint(
            model_name='workschedule',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['ACTIVE', 'INACTIVE', 'ARCHIVED'])), name='ck_work_schedules_status'),
        ),
        migrations.AddConstraint(
            model_name='workschedule',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL('weekly_minutes > 0', [], output_field=models.BooleanField())), name='ck_work_schedules_weekly_minutes_positive'),
        ),
        migrations.AddConstraint(
            model_name='workschedule',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL('late_grace_minutes >= 0', [], output_field=models.BooleanField())), name='ck_work_schedules_late_grace_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='workschedule',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL('early_leave_grace_minutes >= 0', [], output_field=models.BooleanField())), name='ck_work_schedules_early_grace_non_negative'),
        ),
        migrations.AddIndex(
            model_name='scheduleday',
            index=models.Index(fields=['schedule'], name='ix_schedule_days_schedule_id'),
        ),
        migrations.AddConstraint(
            model_name='scheduleday',
            constraint=models.UniqueConstraint(fields=('schedule', 'weekday'), name='uq_schedule_days_weekday'),
        ),
        migrations.AddConstraint(
            model_name='scheduleday',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL('weekday >= 1 AND weekday <= 7', [], output_field=models.BooleanField())), name='ck_schedule_days_weekday_range'),
        ),
        migrations.AddConstraint(
            model_name='scheduleday',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL('NOT is_working_day OR (start_time IS NOT NULL AND end_time IS NOT NULL)', [], output_field=models.BooleanField())), name='ck_schedule_days_working_day_has_time'),
        ),
        migrations.AddIndex(
            model_name='employeescheduleassignment',
            index=models.Index(fields=['organization'], name='ix_employee_schedule_assignments_organization_id'),
        ),
        migrations.AddIndex(
            model_name='employeescheduleassignment',
            index=models.Index(fields=['employee'], name='ix_employee_schedule_assignments_employee_id'),
        ),
        migrations.AddIndex(
            model_name='employeescheduleassignment',
            index=models.Index(fields=['schedule'], name='ix_employee_schedule_assignments_schedule_id'),
        ),
        migrations.AddConstraint(
            model_name='employeescheduleassignment',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL('valid_to IS NULL OR valid_to >= valid_from', [], output_field=models.BooleanField())), name='ck_employee_schedule_assignments_valid_period'),
        ),
        migrations.AddConstraint(
            model_name='employeescheduleassignment',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('employee_id', '='), (models.Func(models.F('valid_from'), models.F('valid_to'), models.Value('[]'), function='daterange', output_field=django.contrib.postgres.fields.ranges.DateRangeField()), '&&')], name='ex_employee_schedule_assignments_overlap'),
        ),
    ]
