# Generated by Django 5.2.17 on 2026-09-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarexception',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
