# Generated by Django 5.2.17 on 2026-09-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0001_initial'),
        ('organizations', '0001_initial'),
        ('schedules', '0002_calendarexception_reason'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='calendarexception',
            name='uq_calendar_exceptions_office_date',
        ),
        migrations.RemoveConstraint(
            model_name='calendarexception',
            name='uq_calendar_exceptions_org_date',
        ),
        migrations.AddField(
            model_name='calendarexception',
            name='is_active',
            field=models.BooleanField(db_default=True),
        ),
        migrations.AddConstraint(
            model_name='calendarexception',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('office__isnull', False)), fields=('office', 'date'), name='uq_calendar_exceptions_office_date'),
        ),
        migrations.AddConstraint(
            model_name='calendarexception',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('office__isnull', True)), fields=('organization', 'date'), name='uq_calendar_exceptions_org_date'),
        ),
    ]
