# Generated by Django 5.2.17 on 2026-09-03 18:44

import django.contrib.postgres.functions
import django.db.models.deletion
import django.db.models.functions.text
import humotech.core.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_extensions"),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('default_timezone', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('ARCHIVED', 'ARCHIVED')], max_length=30)),
                ('knowledge_revision', models.IntegerField(db_default=1)),
            ],
            options={
                'verbose_name': 'организация',
                'verbose_name_plural': 'организации',
                'db_table': 'organizations',
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['ACTIVE', 'INACTIVE', 'ARCHIVED'])), name='ck_organizations_status'), models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='uq_organizations_lower_code')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationSetting',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('key', models.CharField(max_length=100)),
                ('value', models.JSONField()),
                ('organization', models.ForeignKey(db_column='organization_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='settings', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'настройка организации',
                'verbose_name_plural': 'настройки организации',
                'db_table': 'organization_settings',
                'indexes': [models.Index(fields=['organization'], name='ix_organization_settings_organization_id')],
                'constraints': [models.UniqueConstraint(models.F('organization'), models.F('key'), name='uq_organization_settings_org_key')],
            },
        ),
    ]
