# Generated by Django 5.2.17 on 2026-09-20 13:47

import django.contrib.postgres.functions
import django.db.models.deletion
import django.db.models.expressions
import humotech.core.functions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0007_probation_period'),
        ('files', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingProgram',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_default=True)),
                ('created_by_user', models.ForeignKey(blank=True, db_column='created_by_user_id', db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(db_column='organization_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'программа ознакомления',
                'verbose_name_plural': 'программы ознакомления',
                'db_table': 'onboarding_programs',
            },
        ),
        migrations.CreateModel(
            name='EmployeeOnboarding',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('INFO_COMPLETED', 'INFO_COMPLETED'), ('POLICIES_IN_PROGRESS', 'POLICIES_IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('BLOCKED_BY_DECLINED_POLICY', 'BLOCKED_BY_DECLINED_POLICY')], max_length=30)),
                ('invited_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('info_completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_reminder_at', models.DateTimeField(blank=True, null=True)),
                ('chat_message_id', models.BigIntegerField(blank=True, null=True)),
                ('created_by_user', models.ForeignKey(blank=True, db_column='created_by_user_id', db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(db_column='employee_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='onboarding', to='employees.employee')),
                ('organization', models.ForeignKey(db_column='organization_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('program', models.ForeignKey(db_column='program_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='onboarding.onboardingprogram')),
            ],
            options={
                'verbose_name': 'ознакомление сотрудника',
                'verbose_name_plural': 'ознакомления сотрудников',
                'db_table': 'employee_onboarding',
            },
        ),
        migrations.CreateModel(
            name='OnboardingSection',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('position', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('button_label', models.CharField(max_length=100)),
                ('version', models.IntegerField(db_default=1)),
                ('organization', models.ForeignKey(db_column='organization_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('program', models.ForeignKey(db_column='program_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='onboarding.onboardingprogram')),
            ],
            options={
                'verbose_name': 'карточка ознакомления',
                'verbose_name_plural': 'карточки ознакомления',
                'db_table': 'onboarding_sections',
            },
        ),
        migrations.CreateModel(
            name='EmployeeSectionAcknowledgement',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('section_version', models.IntegerField()),
                ('acknowledged_at', models.DateTimeField()),
                ('telegram_user_id', models.BigIntegerField(blank=True, null=True)),
                ('onboarding', models.ForeignKey(db_column='onboarding_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='acknowledgements', to='onboarding.employeeonboarding')),
                ('organization', models.ForeignKey(db_column='organization_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('section', models.ForeignKey(db_column='section_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='acknowledgements', to='onboarding.onboardingsection')),
            ],
            options={
                'verbose_name': 'подтверждение карточки',
                'verbose_name_plural': 'подтверждения карточек',
                'db_table': 'employee_onboarding_section_acks',
            },
        ),
        migrations.CreateModel(
            name='PolicyDocument',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_mandatory', models.BooleanField(db_default=True)),
                ('position', models.IntegerField(db_default=1)),
                ('created_by_user', models.ForeignKey(blank=True, db_column='created_by_user_id', db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(db_column='organization_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'обязательный документ',
                'verbose_name_plural': 'обязательные документы',
                'db_table': 'policy_documents',
            },
        ),
        migrations.CreateModel(
            name='PolicyDocumentVersion',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('version', models.CharField(max_length=20)),
                ('summary', models.TextField()),
                ('body', models.TextField(blank=True, null=True)),
                ('agree_label', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('PUBLISHED', 'PUBLISHED'), ('ARCHIVED', 'ARCHIVED')], max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(db_column='document_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='onboarding.policydocument')),
                ('file', models.ForeignKey(blank=True, db_column='file_id', db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='files.file')),
                ('organization', models.ForeignKey(db_column='organization_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('published_by_user', models.ForeignKey(blank=True, db_column='published_by_user_id', db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'редакция документа',
                'verbose_name_plural': 'редакции документов',
                'db_table': 'policy_document_versions',
            },
        ),
        migrations.CreateModel(
            name='EmployeePolicyAcceptance',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('decision', models.CharField(choices=[('ACCEPTED', 'ACCEPTED'), ('DECLINED', 'DECLINED')], max_length=20)),
                ('decided_at', models.DateTimeField()),
                ('telegram_user_id', models.BigIntegerField(blank=True, null=True)),
                ('employee', models.ForeignKey(db_column='employee_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='policy_acceptances', to='employees.employee')),
                ('organization', models.ForeignKey(db_column='organization_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('version', models.ForeignKey(db_column='version_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='acceptances', to='onboarding.policydocumentversion')),
            ],
            options={
                'verbose_name': 'решение по документу',
                'verbose_name_plural': 'решения по документам',
                'db_table': 'employee_policy_acceptances',
            },
        ),
        migrations.AddIndex(
            model_name='onboardingprogram',
            index=models.Index(fields=['organization'], name='ix_onboarding_programs_org_id'),
        ),
        migrations.AddConstraint(
            model_name='onboardingprogram',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uq_onboarding_programs_code'),
        ),
        migrations.AddConstraint(
            model_name='onboardingprogram',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True), ('is_active', True)), fields=('organization',), name='uq_onboarding_programs_active'),
        ),
        migrations.AddIndex(
            model_name='employeeonboarding',
            index=models.Index(fields=['organization'], name='ix_employee_onboarding_organization_id'),
        ),
        migrations.AddIndex(
            model_name='employeeonboarding',
            index=models.Index(fields=['organization', 'status'], name='ix_employee_onboarding_status'),
        ),
        migrations.AddConstraint(
            model_name='employeeonboarding',
            constraint=models.UniqueConstraint(fields=('employee',), name='uq_employee_onboarding_employee'),
        ),
        migrations.AddConstraint(
            model_name='employeeonboarding',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['NOT_STARTED', 'IN_PROGRESS', 'INFO_COMPLETED', 'POLICIES_IN_PROGRESS', 'COMPLETED', 'BLOCKED_BY_DECLINED_POLICY'])), name='ck_employee_onboarding_status'),
        ),
        migrations.AddIndex(
            model_name='onboardingsection',
            index=models.Index(fields=['organization'], name='ix_onboarding_sections_org_id'),
        ),
        migrations.AddIndex(
            model_name='onboardingsection',
            index=models.Index(fields=['program'], name='ix_onboarding_sections_program_id'),
        ),
        migrations.AddConstraint(
            model_name='onboardingsection',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL('position > 0', [], output_field=models.BooleanField())), name='ck_onboarding_sections_position'),
        ),
        migrations.AddConstraint(
            model_name='onboardingsection',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL('version > 0', [], output_field=models.BooleanField())), name='ck_onboarding_sections_version'),
        ),
        migrations.AddConstraint(
            model_name='onboardingsection',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True)), fields=('program', 'position'), name='uq_onboarding_sections_position'),
        ),
        migrations.AddIndex(
            model_name='employeesectionacknowledgement',
            index=models.Index(fields=['organization'], name='ix_onboarding_acks_org_id'),
        ),
        migrations.AddIndex(
            model_name='employeesectionacknowledgement',
            index=models.Index(fields=['onboarding'], name='ix_onboarding_acks_onboarding_id'),
        ),
        migrations.AddConstraint(
            model_name='employeesectionacknowledgement',
            constraint=models.UniqueConstraint(fields=('onboarding', 'section', 'section_version'), name='uq_onboarding_section_acks'),
        ),
        migrations.AddIndex(
            model_name='policydocument',
            index=models.Index(fields=['organization'], name='ix_policy_documents_org_id'),
        ),
        migrations.AddConstraint(
            model_name='policydocument',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uq_policy_documents_code'),
        ),
        migrations.AddIndex(
            model_name='policydocumentversion',
            index=models.Index(fields=['organization'], name='ix_policy_versions_org_id'),
        ),
        migrations.AddIndex(
            model_name='policydocumentversion',
            index=models.Index(fields=['document'], name='ix_policy_versions_document_id'),
        ),
        migrations.AddConstraint(
            model_name='policydocumentversion',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'PUBLISHED', 'ARCHIVED'])), name='ck_policy_versions_status'),
        ),
        migrations.AddConstraint(
            model_name='policydocumentversion',
            constraint=models.UniqueConstraint(fields=('document', 'version'), name='uq_policy_versions_number'),
        ),
        migrations.AddConstraint(
            model_name='policydocumentversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PUBLISHED')), fields=('document',), name='uq_policy_versions_published'),
        ),
        migrations.AddConstraint(
            model_name='policydocumentversion',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL("status <> 'PUBLISHED' OR published_at IS NOT NULL", [], output_field=models.BooleanField())), name='ck_policy_versions_published_at'),
        ),
        migrations.AddIndex(
            model_name='employeepolicyacceptance',
            index=models.Index(fields=['organization'], name='ix_policy_acceptances_org_id'),
        ),
        migrations.AddIndex(
            model_name='employeepolicyacceptance',
            index=models.Index(fields=['employee'], name='ix_policy_acceptances_employee_id'),
        ),
        migrations.AddIndex(
            model_name='employeepolicyacceptance',
            index=models.Index(fields=['version'], name='ix_policy_acceptances_version_id'),
        ),
        migrations.AddConstraint(
            model_name='employeepolicyacceptance',
            constraint=models.CheckConstraint(condition=models.Q(('decision__in', ['ACCEPTED', 'DECLINED'])), name='ck_policy_acceptances_decision'),
        ),
        migrations.AddConstraint(
            model_name='employeepolicyacceptance',
            constraint=models.UniqueConstraint(fields=('employee', 'version'), name='uq_policy_acceptances_employee_version'),
        ),
    ]
