"""Разделы материалов и срок ознакомления.

  * `policy_categories` — раздел: название, описание, ответственный.
    Документ ссылается на раздел необязательным ключом; история
    подтверждений от раздела не зависит;
  * `employee_onboarding.due_date` — до какого дня пройти. У тех, кого
    включили раньше, остаётся пустым: срок задним числом не выдумываем.

Ключи — в том же виде, что и остальные (см. 0002): RESTRICT, у автора —
SET NULL.
"""

# Generated by Django 5.2.17 on 2026-09-25 09:24

import django.contrib.postgres.functions
import django.db.models.deletion
import humotech.core.functions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_probation_period'),
        ('onboarding', '0004_update_required_status'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeonboarding',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PolicyCategory',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('position', models.IntegerField(db_default=1)),
                ('created_by_user', models.ForeignKey(blank=True, db_column='created_by_user_id', db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(db_column='organization_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('owner_employee', models.ForeignKey(blank=True, db_column='owner_employee_id', db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='employees.employee')),
            ],
            options={
                'verbose_name': 'раздел материалов',
                'verbose_name_plural': 'разделы материалов',
                'db_table': 'policy_categories',
            },
        ),
        migrations.AddField(
            model_name='policydocument',
            name='category',
            field=models.ForeignKey(blank=True, db_column='category_id', db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='onboarding.policycategory'),
        ),
        migrations.AddIndex(
            model_name='policycategory',
            index=models.Index(fields=['organization'], name='ix_policy_categories_org_id'),
        ),
    ]
