# Generated by Django 5.2.17 on 2026-09-03 19:00

import django.contrib.postgres.functions
import django.db.models.deletion
import django.db.models.expressions
import humotech.core.functions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_extensions"),
        ('devices', '0001_initial'),
        ('employees', '0001_initial'),
        ('offices', '0001_initial'),
        ('organizations', '0001_initial'),
        ('qr_codes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceEvent',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('event_type', models.CharField(choices=[('ENTRY', 'ENTRY'), ('EXIT', 'EXIT')], max_length=20)),
                ('source', models.CharField(choices=[('QR', 'QR'), ('MANUAL', 'MANUAL'), ('IMPORT', 'IMPORT')], max_length=20)),
                ('verification_status', models.CharField(choices=[('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED'), ('REVIEW', 'REVIEW')], max_length=20)),
                ('occurred_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow())),
                ('qr_nonce_hash', models.TextField(blank=True, null=True)),
                ('qr_issued_at', models.DateTimeField(blank=True, null=True)),
                ('qr_expires_at', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_accuracy_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('inside_geofence', models.BooleanField(blank=True, null=True)),
                ('inside_office_network', models.BooleanField(blank=True, null=True)),
                ('client_event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('event_metadata', models.JSONField(blank=True, db_column='metadata', null=True)),
                ('employee', models.ForeignKey(db_column='employee_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_events', to='employees.employee')),
                ('employee_device', models.ForeignKey(blank=True, db_column='employee_device_id', db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='devices.employeedevice')),
                ('office', models.ForeignKey(db_column='office_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_events', to='offices.office')),
                ('organization', models.ForeignKey(db_column='organization_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('qr_display_session', models.ForeignKey(blank=True, db_column='qr_display_session_id', db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='qr_codes.qrdisplaysession')),
                ('qr_point', models.ForeignKey(blank=True, db_column='qr_point_id', db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='qr_codes.officeqrpoint')),
            ],
            options={
                'verbose_name': 'отметка',
                'verbose_name_plural': 'отметки',
                'db_table': 'attendance_events',
            },
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED'), ('CORRECTED', 'CORRECTED'), ('INVALID', 'INVALID')], max_length=20)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(db_column='employee_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_sessions', to='employees.employee')),
                ('entry_event', models.ForeignKey(db_column='entry_event_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='attendance.attendanceevent')),
                ('exit_event', models.ForeignKey(blank=True, db_column='exit_event_id', db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='attendance.attendanceevent')),
                ('office', models.ForeignKey(db_column='office_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_sessions', to='offices.office')),
                ('organization', models.ForeignKey(db_column='organization_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'рабочая сессия',
                'verbose_name_plural': 'рабочие сессии',
                'db_table': 'attendance_sessions',
            },
        ),
        migrations.CreateModel(
            name='AttendanceCorrectionRequest',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('requested_entry_at', models.DateTimeField(blank=True, null=True)),
                ('requested_exit_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('SUBMITTED', 'SUBMITTED'), ('IN_REVIEW', 'IN_REVIEW'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('CANCELLED', 'CANCELLED')], max_length=20)),
                ('submitted_at', models.DateTimeField()),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(db_column='employee_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='correction_requests', to='employees.employee')),
                ('organization', models.ForeignKey(db_column='organization_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('reviewed_by_user', models.ForeignKey(blank=True, db_column='reviewed_by_user_id', db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('attendance_session', models.ForeignKey(blank=True, db_column='attendance_session_id', db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correction_requests', to='attendance.attendancesession')),
            ],
            options={
                'verbose_name': 'заявка на исправление отметки',
                'verbose_name_plural': 'заявки на исправление отметок',
                'db_table': 'attendance_correction_requests',
            },
        ),
        migrations.AddIndex(
            model_name='attendanceevent',
            index=models.Index(fields=['organization'], name='ix_attendance_events_organization_id'),
        ),
        migrations.AddIndex(
            model_name='attendanceevent',
            index=models.Index(fields=['employee', '-occurred_at'], name='ix_attendance_events_employee_time'),
        ),
        migrations.AddIndex(
            model_name='attendanceevent',
            index=models.Index(fields=['office', '-occurred_at'], name='ix_attendance_events_office_time'),
        ),
        migrations.AddIndex(
            model_name='attendanceevent',
            index=models.Index(fields=['qr_point', '-occurred_at'], name='ix_attendance_events_qr_point_time'),
        ),
        migrations.AddIndex(
            model_name='attendanceevent',
            index=models.Index(fields=['verification_status', '-occurred_at'], name='ix_attendance_events_status_time'),
        ),
        migrations.AddConstraint(
            model_name='attendanceevent',
            constraint=models.CheckConstraint(condition=models.Q(('event_type__in', ['ENTRY', 'EXIT'])), name='ck_attendance_events_event_type'),
        ),
        migrations.AddConstraint(
            model_name='attendanceevent',
            constraint=models.CheckConstraint(condition=models.Q(('source__in', ['QR', 'MANUAL', 'IMPORT'])), name='ck_attendance_events_source'),
        ),
        migrations.AddConstraint(
            model_name='attendanceevent',
            constraint=models.CheckConstraint(condition=models.Q(('verification_status__in', ['ACCEPTED', 'REJECTED', 'REVIEW'])), name='ck_attendance_events_verification_status'),
        ),
        migrations.AddConstraint(
            model_name='attendanceevent',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL("source <> 'QR' OR qr_point_id IS NOT NULL", [], output_field=models.BooleanField())), name='ck_attendance_events_qr_requires_point'),
        ),
        migrations.AddConstraint(
            model_name='attendanceevent',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL('qr_expires_at IS NULL OR qr_issued_at IS NULL OR qr_expires_at > qr_issued_at', [], output_field=models.BooleanField())), name='ck_attendance_events_qr_expiry_after_issue'),
        ),
        migrations.AddConstraint(
            model_name='attendanceevent',
            constraint=models.UniqueConstraint(condition=models.Q(('qr_nonce_hash__isnull', False), ('verification_status', 'ACCEPTED')), fields=('employee', 'qr_nonce_hash', 'event_type'), name='uq_attendance_events_nonce'),
        ),
        migrations.AddConstraint(
            model_name='attendanceevent',
            constraint=models.UniqueConstraint(condition=models.Q(('client_event_id__isnull', False)), fields=('employee', 'client_event_id'), name='uq_attendance_events_client_event'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['organization'], name='ix_attendance_sessions_organization_id'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['employee', '-started_at'], name='ix_attendance_sessions_employee_time'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['office', '-started_at'], name='ix_attendance_sessions_office_time'),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['OPEN', 'CLOSED', 'CORRECTED', 'INVALID'])), name='ck_attendance_sessions_status'),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL('ended_at IS NULL OR ended_at >= started_at', [], output_field=models.BooleanField())), name='ck_attendance_sessions_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL('duration_seconds IS NULL OR duration_seconds >= 0', [], output_field=models.BooleanField())), name='ck_attendance_sessions_duration_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL("status <> 'CLOSED' OR (ended_at IS NOT NULL AND exit_event_id IS NOT NULL)", [], output_field=models.BooleanField())), name='ck_attendance_sessions_closed_has_exit'),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('employee',), name='uq_attendance_sessions_one_open'),
        ),
        migrations.AddIndex(
            model_name='attendancecorrectionrequest',
            index=models.Index(fields=['organization'], name='ix_attendance_correction_requests_organization_id'),
        ),
        migrations.AddIndex(
            model_name='attendancecorrectionrequest',
            index=models.Index(fields=['employee'], name='ix_attendance_correction_requests_employee_id'),
        ),
        migrations.AddConstraint(
            model_name='attendancecorrectionrequest',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'SUBMITTED', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'CANCELLED'])), name='ck_attendance_correction_requests_status'),
        ),
        migrations.AddConstraint(
            model_name='attendancecorrectionrequest',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL('requested_entry_at IS NOT NULL OR requested_exit_at IS NOT NULL', [], output_field=models.BooleanField())), name='ck_attendance_correction_requests_something_requested'),
        ),
        migrations.AddConstraint(
            model_name='attendancecorrectionrequest',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL('requested_exit_at IS NULL OR requested_entry_at IS NULL OR requested_exit_at >= requested_entry_at', [], output_field=models.BooleanField())), name='ck_attendance_correction_requests_exit_after_entry'),
        ),
    ]
