# Generated by Django 5.2.17 on 2026-09-17 16:24

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('devices', '0001_initial'),
        ('employees', '0005_photo_foreign_key'),
        ('offices', '0001_initial'),
        ('organizations', '0001_initial'),
        ('qr_codes', '0004_office_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceevent',
            name='distance_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='attendanceevent',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL('distance_m IS NULL OR distance_m >= 0', [], output_field=models.BooleanField())), name='ck_attendance_events_distance_non_negative'),
        ),
    ]
