# Generated by Django 5.2.17 on 2026-09-18 13:59

import django.contrib.postgres.functions
import django.db.models.deletion
import humotech.core.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_office_setup'),
        ('employees', '0006_termination_reason'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayNotice',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('day', models.DateField()),
                ('kind', models.CharField(choices=[('LATE', 'LATE'), ('ABSENT', 'ABSENT')], max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('noticed_at', models.DateTimeField()),
                ('employee', models.ForeignKey(db_column='employee_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='day_notices', to='employees.employee')),
                ('organization', models.ForeignKey(db_column='organization_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'сообщение сотрудника о дне',
                'verbose_name_plural': 'сообщения сотрудников о дне',
                'db_table': 'attendance_day_notices',
                'indexes': [models.Index(fields=['organization', 'day'], name='ix_attendance_day_notices_org_day')],
                'constraints': [models.CheckConstraint(condition=models.Q(('kind__in', ['LATE', 'ABSENT'])), name='ck_attendance_day_notices_kind'), models.UniqueConstraint(fields=('employee', 'day'), name='uq_attendance_day_notices_employee_day')],
            },
        ),
    ]
