# Generated by Django 5.2.17 on 2026-09-03 19:00

import django.contrib.postgres.functions
import django.db.models.deletion
import django.db.models.expressions
import humotech.core.functions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_extensions"),
        ('offices', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeQrPoint',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('direction_mode', models.CharField(choices=[('ENTRY', 'ENTRY'), ('EXIT', 'EXIT'), ('BOTH', 'BOTH')], max_length=20)),
                ('qr_mode', models.CharField(choices=[('STATIC', 'STATIC'), ('ROTATING', 'ROTATING')], db_default='ROTATING', max_length=20)),
                ('static_token_hash', models.TextField(blank=True, null=True)),
                ('rotation_seconds', models.IntegerField(blank=True, null=True)),
                ('token_version', models.IntegerField(db_default=1)),
                ('require_geolocation', models.BooleanField(db_default=False)),
                ('require_office_network', models.BooleanField(db_default=False)),
                ('allowed_location_accuracy_m', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_default=True)),
                ('office', models.ForeignKey(db_column='office_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='qr_points', to='offices.office')),
                ('organization', models.ForeignKey(db_column='organization_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'QR-точка',
                'verbose_name_plural': 'QR-точки',
                'db_table': 'office_qr_points',
            },
        ),
        migrations.CreateModel(
            name='QrDisplaySession',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=humotech.core.functions.TransactionNow(), editable=False)),
                ('display_identifier_hash', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('EXPIRED', 'EXPIRED'), ('REVOKED', 'REVOKED'), ('CLOSED', 'CLOSED')], max_length=20)),
                ('started_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(db_column='organization_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('qr_point', models.ForeignKey(db_column='qr_point_id', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='display_sessions', to='qr_codes.officeqrpoint')),
                ('started_by_user', models.ForeignKey(blank=True, db_column='started_by_user_id', db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'сессия показа QR',
                'verbose_name_plural': 'сессии показа QR',
                'db_table': 'qr_display_sessions',
            },
        ),
        migrations.AddIndex(
            model_name='officeqrpoint',
            index=models.Index(fields=['organization'], name='ix_office_qr_points_organization_id'),
        ),
        migrations.AddIndex(
            model_name='officeqrpoint',
            index=models.Index(fields=['office'], name='ix_office_qr_points_office_id'),
        ),
        migrations.AddConstraint(
            model_name='officeqrpoint',
            constraint=models.UniqueConstraint(fields=('office', 'code'), name='uq_office_qr_points_office_code'),
        ),
        migrations.AddConstraint(
            model_name='officeqrpoint',
            constraint=models.CheckConstraint(condition=models.Q(('direction_mode__in', ['ENTRY', 'EXIT', 'BOTH'])), name='ck_office_qr_points_direction_mode'),
        ),
        migrations.AddConstraint(
            model_name='officeqrpoint',
            constraint=models.CheckConstraint(condition=models.Q(('qr_mode__in', ['STATIC', 'ROTATING'])), name='ck_office_qr_points_qr_mode'),
        ),
        migrations.AddConstraint(
            model_name='officeqrpoint',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL("(qr_mode = 'STATIC' AND static_token_hash IS NOT NULL) OR (qr_mode = 'ROTATING' AND rotation_seconds IS NOT NULL)", [], output_field=models.BooleanField())), name='ck_office_qr_points_mode_requires_fields'),
        ),
        migrations.AddConstraint(
            model_name='officeqrpoint',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL('rotation_seconds IS NULL OR (rotation_seconds >= 15 AND rotation_seconds <= 300)', [], output_field=models.BooleanField())), name='ck_office_qr_points_rotation_seconds_range'),
        ),
        migrations.AddConstraint(
            model_name='officeqrpoint',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL('token_version > 0', [], output_field=models.BooleanField())), name='ck_office_qr_points_token_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='officeqrpoint',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL('allowed_location_accuracy_m IS NULL OR allowed_location_accuracy_m > 0', [], output_field=models.BooleanField())), name='ck_office_qr_points_accuracy_positive'),
        ),
        migrations.AddIndex(
            model_name='qrdisplaysession',
            index=models.Index(fields=['organization'], name='ix_qr_display_sessions_organization_id'),
        ),
        migrations.AddIndex(
            model_name='qrdisplaysession',
            index=models.Index(fields=['qr_point'], name='ix_qr_display_sessions_qr_point_id'),
        ),
        migrations.AddConstraint(
            model_name='qrdisplaysession',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['ACTIVE', 'EXPIRED', 'REVOKED', 'CLOSED'])), name='ck_qr_display_sessions_status'),
        ),
        migrations.AddConstraint(
            model_name='qrdisplaysession',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.expressions.RawSQL('ended_at IS NULL OR ended_at >= started_at', [], output_field=models.BooleanField())), name='ck_qr_display_sessions_end_after_start'),
        ),
    ]
